common/response.go
This is a quick fix for #82, but the root cause is still unknown.
We added debugging information for when this happens in 0451efba, so it's the same issue that will need a deeper lifecycle fix. I'll create a new issue for it.
=> Fix getting response body if Frame is nil

common/logger.go, common/network_manager.go, common/response.go, tests/network_manager_test.go, testutils/browsertest/browsertest.go, testutils/logrus_hook.go
This skips handling of `data:` URLs as early as possible, so that we don't emit empty metrics for them.
These are typically found in CSS, e.g.: `background:url("data:image/svg+xml;base64,PHN2ZyB3...")`.
=> Skip request handling of data: URLs

chromium/browser_type.go, common/browser_process.go, common/context.go, common/frame_session.go, common/helpers.go
This PR adds a cross-platform browser process killer.
* `k6Throw` kills any lingering browser processes in a cross-platform way.
* Saves the process ID to the context when launching a new browser.
We need to update `k6common.Throw` to our `k6Throw` for this to work stable. And I manually tested this with 100 browsers on my Mac. It cleaned up all the lingering processes. Automated tests are missing for now. I'm planning to do these in a separate PR.
As I said in the PR this is a temporary fix:
https://github.com/grafana/xk6-browser/issues/93#issuecomment-966911692
Closes: #93
=> Cross-platform browser process killer

common/browser_context_options.go, common/frame_session.go, common/page.go, tests/browser_context_options_test.go, tests/page_test.go
Closes #111
Also fixes it for `Page.SetExtraHTTPHeaders()`.
=> Fix panic setting extra HTTP headers

go.mod, go.sum, main.go
=> Update k6 dependency and JS module structure to v0.35.0

common/frame.go
For very quick requests there's a race condition between when we [set `f.networkIdleCtx` to nil](https://github.com/grafana/xk6-browser/blob/baaf58caef73370f1659c30b3d3a989ddcd8da27/common/frame.go#L273) as part of the `FrameManager.requestStarted()` call, and when we [start the idle timer again in `FrameManager.requestFinished()`](https://github.com/grafana/xk6-browser/blob/baaf58caef73370f1659c30b3d3a989ddcd8da27/common/frame.go#L290).
This fix uses a channel instead of storing a mutex, which is safer.
Fixes #109
=> Fix nil pointer panic on Frame.networkIdleCtx

common/frame.go
See: #126 for the explanation.
This also fixes Tom's oldest script problems from #49 while in `headless: true` mode. But still no luck with `headless: false` mode.
=> Fix clearLifecycle bug of nil request

.github/workflows/e2e.yml
This PR is for resolving [this error](https://github.com/grafana/xk6-browser/runs/4324594157?check_suite_focus=true).
Thanks, @MStoykov for the heads up 🙇 
```
go: downloading go.k6.io/k6 v0.35.0
go: go.k6.io/k6@v0.35.0 requires
gopkg.in/guregu/null.v2@v2.1.2: unrecognized import path "gopkg.in/guregu/null.v2": reading https://gopkg.in/guregu/null.v2?go-get=1: 502 Bad Gateway
server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/guregu/null.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
=> Fix/e2e cannot talk to GitHub issue

chromium/browser_type.go, common/browser.go, common/element_handle.go, common/frame.go, common/page.go
I cherry-picked this one from #129 as a separate PR.
@imiric So let's merge this one before merging #129.
=> Fix slice make calls extension wide

tests/metrics_test.go, tests/network_manager_test.go
This adds a missing test for #40, and all other metrics emitted for `page.goto()`.
It uses a slightly modified version of the [`assertRequestMetricsEmittedSingle` helper from k6](https://github.com/grafana/k6/blob/804203bcf574da57cd05d67b39f03d05c54523ab/js/modules/k6/http/request_test.go#L109).
=> Add metrics emission test

common/barrier_test.go, common/browser.go, common/connection.go, common/connection_test.go, common/element_handle.go, common/execution_context.go, common/frame.go, common/frame_manager.go, common/frame_session.go, common/frame_test.go, common/helpers_test.go, common/logger.go, common/page.go, common/screenshotter.go, common/session.go, common/session_test.go
I added a few more bug fixes after [receiving another script that fails with this error](https://community.k6.io/t/unable-to-properly-navigate-to-url/2567/4) (_from a user in our community_). Now we no longer try to attach a frame or worker if the browser is already closed. These commits solved the user's issues: 77949eb and a3aea00.
This PR only focuses on fixing and gracefully handling _"cannot create frame session"_ problem in #125 with this afe4550c commit. Later on, within other commits, it fixes related data race issues, makes some refactorings, and cleans things up.
The problem was about the propagation of #49 into this one. We throw an error when we cannot find a context with a given id while a new `FrameSession` is trying to boot up. So the extension is already in a terminating …
=> Fix/125 cannot create frame session (context canceled)

chromium/browser_type.go, common/frame.go, common/frame_manager.go, common/page.go, common/request.go, common/screenshotter.go
This PR skips setting the mainframe if it is already the same.
It also adds some sanity checks and protects the mainframe field behind a mutex in places that forgot to use it.
=> Improve mainframe handling

common/connection.go, common/execution_context.go
This PR improves execution context logs by including `Frame.ID` and `ExecutionContext.ID`. So we can better understand the originating `Frame` if an error ever occurs again.
=> Improve execution context logs

common/browser.go, common/browser_context.go, common/browser_test.go, common/event_emitter.go, common/frame_manager.go, common/frame_session.go, common/launch.go, tests/page_test.go
This PR fixes [the problem](https://github.com/grafana/xk6-browser/issues/187) and adds an [integration test](https://github.com/grafana/xk6-browser/blob/cde9f02d2012356e852e375a03cce2ecddab0285/tests/page_test.go#L106-L113) and [unit test](https://github.com/grafana/xk6-browser/blob/cde9f02d2012356e852e375a03cce2ecddab0285/common/browser_test.go). It also refactors related code for better maintainability.
**Explanation of the fixes:**
`FrameManager.WaitForFrameNavigation` wasn't returning when the context is canceled, and then it was trying to read a `nil` event, resulting in a `nil pointer` error. [Now it returns](https://github.com/grafana/xk6-browser/blob/cde9f02d2012356e852e375a03cce2ecddab0285/common/frame_manager.go#L705-L710) and prevents this problem. There is no need to throw an …
=> Fix WaitForFrameNavigation nil pointer bug

common/element_handle.go, common/execution_context.go, common/frame.go, common/frame_test.go, common/js_handle.go, common/page.go, common/screenshotter.go, tests/element_handle_click_test.go
This PR refactors `ElementHandle`'s evaluate calls that happen through the `ExecutionContext,` which are repetitive. This is not a critical change, but I worked on it while fixing #170 and wanted to create a separate PR.
We now provide two new unexported methods:
* [`evalWithScript`](https://github.com/grafana/xk6-browser/blob/9b773bffd96c063363e3897d06b687ec79f1d64f/common/element_handle.go#L1428-L1442): Runs a javascript code in the current `ElementHandle` scope and provides an ability to use the injected script's functions. In the previous code version, each `ElementHandle` function needs to pass the current `ElementHandle` and call `getInjectedScript` and then pass it to the `ExecutionContext`'s `evaluate` call. This function makes this easier.
* …
=> Refactor ElementHandle evaluate calls

common/browser.go, common/browser_context.go, common/frame_manager.go, common/frame_session.go, common/network_manager.go, common/network_manager_test.go, common/session.go, tests/network_manager_test.go, tests/test_browser.go
Partially implements #105
I decided to leave most of the previous request interception code intact (`api.Route`, etc.), except for the non-functional parts (47b0121). This will be useful once we expose this API to JS, which seems to have been the original idea, and is [what Playwright and Puppeteer already do](https://github.com/grafana/xk6-browser/issues/105#issuecomment-1016655405). For now, the [`Fetch` CDP domain](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/) is only enabled and used internally.
=> Add request blocking based on k6 `blockHostnames` option

common/element_handle.go, common/execution_context.go, common/frame.go, common/frame_test.go, common/js_handle.go, common/page.go, common/screenshotter.go, tests/element_handle_click_test.go
I'd like to revert #196, remove the `QueryAll` fix and add it to the actual fix PR. I'll also put the other refactorings in #195 to another PR—leave it only with the fix. So we can better point it out in the release and have a better history.
=> Revert "Refactor ElementHandle evaluate calls"

common/network_manager.go, common/session.go
Resolves https://github.com/grafana/xk6-browser/pull/204#discussion_r796395070
I prefer the anonymous interface approach rather than coming up with some common one we're not sure we'll have a need for yet.
=> Make session an anonymous interface within NetworkManager

chromium/browser_type.go, chromium/browser_type_test.go, examples/hosts.js
This translates [k6's `hosts` option](https://k6.io/docs/using-k6/options/#hosts) into [Chrome's `host-resolver-rules` option](https://datacadamia.com/web/browser/chrome#dns_resolver). There's no way that I could see to set this via CDP, so it needs to be done at launch. And of course, re-implemented for Firefox once we support it, though judging by [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1523367), there doesn't seem to be an equivalent option (yet?).
This is based on #206, so that should be merged first.
Closes #105
=> Add support for k6's `hosts` option

.github/workflows/all.yaml, chromium/allocator.go, chromium/browser_type.go, common/browser_context.go, common/element_handle.go, common/frame.go, common/frame_manager.go, common/frame_session.go
This PR fixes linter errors as reported by golang-ci-lint with its default settings.
=> Fix general linter errors

common/network_manager.go, common/response.go, tests/network_manager_test.go
This is related to #90, but doesn't really fix the issue as the current behavior is correct. See [this comment](https://github.com/grafana/xk6-browser/issues/90#issuecomment-966477394).
Essentially `Frame` being nil is a valid state for responses to preflight/`OPTIONS` requests, so the fix in b2052bb is all we need to do for handling this case.
What this PR does is:
- move the `data_received` metric emission to the `LoadingFinished` event handler, which [according to this comment](https://github.com/ChromeDevTools/devtools-protocol/issues/44#issuecomment-320127404) is more reliable. This results in more accurate `data_received` metric values.
Before, on `main` (54cd293) with the script from [this comment](https://github.com/grafana/xk6-browser/pull/117#issuecomment-1002521620):
``` …
```
=> More reliable response body size and `data_received` metric emission

.github/workflows/all.yaml
This reverts commit 2a5a92c8294fd5e7ced48e56afb380aea04406b7.
We're planning to add more linters, see: #216 and #58. So we've decided to re-enable the `--new-from-rev` option. See the discussion:
- https://github.com/grafana/xk6-browser/pull/216#issuecomment-1029781140
- https://github.com/grafana/xk6-browser/pull/216#issuecomment-1029797172
=> Revert "Remove BASEREV and new-from-rev from CI workflow"

common/element_handle.go, common/helpers.go, tests/element_handle_click_test.go
When you run tests only once, there is no problem, however if you run
them multiple times using the count flag, k6ThrowOnce kicks in and
cause k6ThrowUnsafe not to run. This happens because the Go test runner
compiles the test binary only once and uses it to run the test in the
same process.
I don't know why but somehow we or Goja have fixed the issue in k6Throw
and now this commit entirely removes the k6Throw synchronization.
I tested it several times and I didn't observe any issues.
Fixes: #218
=> Remove k6ThrowOnce and friends

common/element_handle.go, common/element_handle_test.go, common/helpers.go
This PR is a part of refactoring for #215. It moves `errorFromDOMError` into `ElementHandle` to increase [cohesion](https://en.wikipedia.org/wiki/Cohesion_(computer_science)). Also, it adds a test. But the test doesn't check for every error value to not bind test code to code under test.
Another reason I used a map in the function was that the cyclomatic complexity of the function was 19. Then again, I don't think that will be a problem because the map is local and won't escape.
=> Refactor: errorFromDOMError with test

.github/workflows/all.yaml
This PR bumps test run timeouts from 1m to 5m as discussed in https://github.com/grafana/xk6-browser/issues/222#issuecomment-1033607328.
=> Bump CI test run timeouts

examples/fillform.js
This removes the `sleep()` and `slowMo` option which were workarounds for the `waitForNavigation()` functionality we already have.
There's no issue for this, but see [this comment](https://github.com/grafana/xk6-browser/issues/200#issuecomment-1032454173).
=> Fix `fillform.js` example

common/element_handle.go, common/element_handle_test.go
This one depends on #225, and it's a part of the tasks in #215.
Things to remember before undrafting.
Abstract away the following first:
Tests:
Further Tests:
=> Unit test queryAll

common/context.go, common/context_test.go
The goroutine may leak if the passed context is canceled before the done channel, even if it is closed afterward.
This doesn't add a test for checking whether the function hangs on the `done` chan if the context gets canceled. I couldn't find a clean way to do that. Please let me know if you have an idea.
Related: #237
=> Fix contextWithDoneChan possible goroutine leak

tests/launch_options_slowmo_test.go
We can skip slow motion tests when we give the `-short` flag. The rest of the tests become 10 seconds faster to run. I think we don't need to run slow-motion tests all the time. I'd like to merge this. WDYT, @imiric?
```
➜  k6b git:(test/skip-slowmo) ✗ go test ./tests -failfast -race
ok  	github.com/grafana/xk6-browser/tests	26.945s
➜  k6b git:(test/skip-slowmo) ✗ go test ./tests -failfast -race -short
ok  	github.com/grafana/xk6-browser/tests	17.964s
```
=> Add test short skip for slow mo tests

common/event_emitter.go, common/frame_manager.go, tests/frame_manager_test.go, tests/static/nav_in_doc.html
Previously `WaitForNavigation` assumed that a `LifecycleEvent` would always be fired, but this is not the case for navigation within the same document (e.g. via anchor links or the History API), so in those cases the call would timeout after 30s.
The fix simply checks if we received a new document, otherwise it skips waiting for the `LifecycleEvent`. Even if that wait didn't time out, it would've failed with a nil pointer panic accessing `event.newDocument.request`.
Closes #226
=> Fix `WaitForNavigation` within the same document

api/browser_context.go, common/browser_context.go, common/frame_session.go, common/network_manager.go, common/page.go, tests/network_manager_test.go
TODO:
Scheduled for later:
Playwright compatibility: Cancel auth when loading is finished or failed
Closes: #203
=> Add basic auth support

tests/frame_manager_test.go
[The previous timings were apparently insufficient in CI](https://github.com/grafana/xk6-browser/runs/5317231381), so this increases them slightly for local test runs (total runtime from ~0.6s to ~0.9s), and hopefully enough in CI for the `WaitForNavigation` timeout not to be reached.
The error manifests itself as a data race in the testing package, but the cause is `WaitForNavigation` panicking because of the timeout.
It also removes `t.Parallel()` from the subtests to hopefully fix #254.
=> `TestWaitForFrameNavigationWithinDocument` fixes for CI

.github/workflows/all.yaml, .github/workflows/e2e.yml
This should hopefully fix the recent failure to sign the binary, see https://github.com/grafana/xk6-browser/runs/5332928690.
I confirmed that it [works on `windows-2019`](https://github.com/grafana/xk6-browser/runs/5334303581), but not on [`windows-latest`](https://github.com/grafana/xk6-browser/runs/5334286611). The strange thing is that [`signtool` is still in the same path](https://github.com/grafana/xk6-browser/runs/5333157519) on both versions, but I'm guessing there's an issue with GH Actions and the way `GITHUB_PATH` works, but it hasn't been documented/reported yet.
=> Fix binary signing on Windows

common/frame.go
`documentHandle` had a data race while switching execution contexts.
This doesn't contain a test because [the test that can reproduce it](https://github.com/grafana/xk6-browser/tree/test/261-frame-nullContext) depends on the correct handling of navigation (which we don't have at this moment v0.2—See: #200 and #258).
Fixes: #261
=> Fix/261 Frame.[nullContext&documentHandle] data race

common/element_handle.go, tests/element_handle_click_test.go, tests/static/non_clickable.html
See issue #266 for an explanation.
`checkHitTargetAt` [now returns with an error](https://github.com/grafana/xk6-browser/pull/270#discussion_r823564738) if the target element is obscured by another element; instead of waiting for the target element to become clickable. This fix is needed before improving the scrolling retry mechanism. Otherwise, we would think that we properly scroll to the target element (and find it clickable) but cannot click on it! Timeout.
`cdppage.GetLayoutMetrics` now uses CSS layout metric when calculating the client's inner width and height (viewport) instead of depending on the first layout parameter ([deprecated](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getLayoutMetrics) and was returning incorrect results).
```diff
- if …
```
=> Fix improve detection of non clickable elements

common/element_handle.go, common/element_handle_options.go, common/frame.go, common/js/actions.go, common/js/scroll_into_view.js, tests/element_handle_click_test.go, tests/static/concealed_link.html
This PR adds an auto-scrolling retry mechanism for all `ElementHandle` pointer actions, including `Click.` So that we can reduce test flakiness which is one of our main goals, as explained earlier by Robin.
According to the [actionability checks](https://playwright.dev/docs/actionability), we can only click on elements on the viewport. However, sometimes an existing element that we want to click can be out of the viewport, and we can't bring it to the viewport even after we scroll.
The previous code only attempts to scroll once, but sometimes it isn't enough. Even after scrolling, the target element stays invisible (see the explanations below).
Try scrolling into it with [various scrolling options (see: scrollIntoViewOptions at the …
=> Make concealed elements clickable

.golangci.yml, common/keyboard.go, tests/keyboard_test.go
Previously pressing some keys like Backspace, Delete, ArrowLeft and AltGraph would panic because we were sending an unsupported `text` argument in the [`Input.dispatchKeyEvent` command](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent). The fix simply does this only for single character keys, and replicates [what Puppeteer does](https://github.com/puppeteer/puppeteer/blob/7659bf92e6f2e4efe8edef6d326cbeca358a995b/src/common/Input.ts#L159).
I added some tests for currently missing functionality that Playwright supports, and will create issues for fixing them (see #284 and #285).
Fixes #239
=> Fix keyboard press of special keys

common/helpers_test.go, tests/browser_test.go, tests/test_browser.go, tests/test_context.go
This adds missing integration tests for `Browser.On` that weren't possible before https://github.com/grafana/k6/pull/2399 was merged. It also does minor refactoring to expose some fields to the test, and allow closing the browser from the test. See the commits for details.
Closes #95
=> Add `Browser.On` integration tests

common/frame.go, common/frame_session.go
This issue happened when receiving `Page.lifecycleEvent`s for different frames which overwrote the global `FrameSession.initTime` value on which the metric value calculation was being done.
The fix is simple: store the `init` time on `Frame` instead and calculate the elapsed time per frame, since the metric emission is done per frame anyway. Unfortunately this exposes another issue worked around by 47d9e82, but should ultimately be fixed by fixing the racy way CDP events are handled; some discussion about this [here](https://github.com/grafana/xk6-browser/discussions/142).
I tried to explain both behaviors in [this comment](https://github.com/grafana/xk6-browser/issues/191#issuecomment-1086016760).
This also does some refactoring to DRY things.
I didn't add any tests since the issue is …
=> Fix negative metric emission

common/element_handle.go, common/execution_context.go, common/frame.go, common/frame_test.go, common/helpers.go, common/page.go, common/remote_object.go, tests/page_test.go
This was done as part of the work for #291, but I split it off into a separate PR to make reviewing easier. See the commits for details.
=> Refactor `ExecutionContext.eval()` and related code

common/frame.go, common/js/injected_script.js
This avoids having to export `continuePolling` and doing the check from the wrapper function in Go, since it's really a JS implementation detail. It also hopefully avoids [the need for a comment explaining internal details of injected_script](https://github.com/grafana/xk6-browser/pull/294/files#r866750362).
=> Do `waitForFunction` predicate truthy check inside `injected_script.js`

common/frame.go, common/frame_options.go, common/frame_options_test.go, common/types.go, common/types_test.go, tests/page_test.go
Previously if the user passed an invalid lifecycle event value in `page.waitForLoadState()` options, we would silently default to `load`, which might not have been the intention. This PR validates the value in `LifecycleEvent.UnmarshalText()` and fails the test with an error if it's invalid. It also reuses the validation in other parts where `LifecycleEvent` is used, such as in `Frame.Goto`, `Frame.SetContent` and `Frame.WaitForNavigation` options, which all used their own validation returning a less informative error.
Ideally lifecycle events should be exported as JS symbols to avoid typo situations, and so that we can have type definitons for them, but this is a stopgap solution until then.
Thanks to @wardbekker for reminding us about this!
=> Add lifecycle event validation to `WaitForLoadState`

release notes/v0.3.0.md
=> Release notes v0.3.0

common/browser.go
This PR fixes #305 by closing browser processes when the context is canceled.
Before this fix, browser processes remained active even after the test or k6 test runs. Hundreds of zombie browser processes were left, especially for local testing.
Fixes: #305
=> Fix zombie browser processes

common/browser_context.go, common/browser_context_options.go, common/browser_context_options_test.go, examples/grant_permission.js
This change is both a fix and enablement of a missing feature.
Previously:
+ `BrowserContext` permissions was failing (see issue #313).
+ `BrowserContext` permissions options were defunct.
Updates:
+ Fixes getting permissions from a script.
+ Grants permissions specified in the `BrowserContext` options when launching a new browser context.
Closes: #313
=> Add grant permissions support to BrowserContext

api/frame.go, api/locator.go, api/page.go, common/frame.go, common/locator.go, common/logger.go, common/page.go, common/page_test.go
This PR aims to add support for creating and returning a new page locator. As explained in issue #308, this PR won't add support for locator options yet.
**Notes to the reviewer**
* Please read issues #100 and #308 to understand what is a `Locator`.
* Check the Playwright documentation to see whether we're implementing the API correctly.
* Thanks!
**TODO**
Closes: #308
=> Implement page.locator(selector)

api/frame.go, api/locator.go, common/frame.go, common/helpers.go, common/locator.go, tests/locator_test.go, tests/static/strict_link.html
This PR adds the ability to click on an element with strict mode via `Locator`. In the test, that is why it expects a panic when the test tries to select multiple link elements. The test also verifies whether the locator can click on an element using the saved selector in the locator.
Pitfalls: Although `locator.Click` forwards the click call to `frame.Click`, I wished there was a way to set the incoming goja value's `strict` property to `true`, instead of (re)parsing the options in `locator.Click`. Do let me know if you know a way to do so.
Closes: #311
=> Add locator.click([options])

README.md
One of the `page.waitForLoadState` names is incorrect.
Produces the following errors when you run the sample:
```
...
ERRO[0008] waitForLoadState error: invalid lifecycle event: "networklidle"; must be one of: load, domcontentloaded, networkidle
running at reflect.methodValueCall (native)
default at n (webpack://perf-customer-scenario-tests/./src/ui/sample.test.ts:22:2(72))
at native  executor=per-vu-iterations scenario=default source=stacktrace
running (00m08.9s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m08.9s/10m0s  1/1 iters, 1 per VU
....
ERRO[0009] err:websocket: close 1006 (abnormal closure): unexpected EOF  category="Connection:handleIOError" elapsed="0 ms" goroutine=82
```
=> Spelling fix for "networkidle"

chromium/browser_type.go, common/barrier_test.go, common/browser.go, common/browser_context.go, common/browser_process.go, common/browser_test.go, common/connection.go, common/connection_test.go, common/execution_context.go, common/frame.go, common/frame_manager.go, common/frame_session.go, common/frame_test.go, common/helpers.go, common/helpers_test.go, common/js_handle.go, common/locator.go, common/network_manager.go, common/network_manager_test.go, common/page.go, common/response.go, common/session.go, common/session_test.go, log/logger.go, log/logger_test.go, logger/logger.go, logger/logger_test.go
Logger is a common process but it should live in its own package, that
is dedicated to all things logging. This will also allow us to easily import
the logger anywhere, helps avoid cyclic imports, it gives us a clean api,
and could allow us to easily migrate to other logging modules if we need.
=> Refactor logger into its own package

common/frame.go, tests/page_test.go
The `Unexpected identifier` error was because of the `return` used outside of a function context. This seemed like a regression introduced by #293, but it also happens on `v0.2.0`, so :man_shrugging:. Casting the `Evaluate()` result to `string` would've failed anyway, so this addresses both issues.
I wanted to add a `Frame.Content()` unit test, but mocking the `ExecutionContext` became troublesome, so I just added this `Page.Content()` integration test instead.
Closes #322
=> Fix `Page.content()`

common/frame.go
This fix will help stop the build from failing.
=> Fix package name from k6 to k6ext

tests/frame_manager_test.go
This change skips running the flaky test: `TestWaitForFrameNavigationWithinDocument` if `SKIP_FLAKY=true` is provided
as an environment variable while running the tests.
The reason behind this change is constantly getting failures breaks the development flow.
**Note:** This environment variable should only be used while in development.
=> Skip TestWaitForFrameNavigationWithinDocument

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/strict_link.html
This PR closes #331.
* Extracts `Frame.dblclick` from `Frame.Dblclick` so that we can use `dblclick` from `Locator.Dblclick`.
* Adds `locator.Dblclick` and a test.
=> Add locator.dblclick([options])

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
This PR closes #359.
* Extracts `Frame.uncheck` from `Frame.Uncheck` so that we can use `uncheck` from `Locator.Uncheck`.
* Adds `locator.Uncheck` and a test.
These other commits from #362 will disappear when we merge #362. I'll rebase this PR if necessary. I based off this branch from #362 because otherwise, a lot of conflicts happen, which is hair pulling 🤦
=> Add locator.Uncheck

api/locator.go, common/element_handle.go, common/frame.go, common/locator.go, common/page.go, tests/locator_test.go
This PR closes #346.
* Extracts `Frame.isChecked` from `Frame.IsChecked` so that we can use `isChecked` from `Locator.IsChecked`.
* Adds `locator.IsChecked` and a test.
* Removes applying slow motion in the `Frame.IsChecked` as discussed in #234.
=> Add locator.IsChecked

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
This PR closes #348.
* Extracts `Frame.isEditable` from `Frame.IsEditable` so that we can use `isEditable` from `Locator.IsEditable`.
* Adds `locator.IsEditable` and a test.
* Removes applying slow motion in the `Frame.IsEditable` as discussed in #234.
=> Add locator.IsEditable

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
This PR closes #349.
* Extracts `Frame.isEnabled` from `Frame.IsEnabled` so that we can use `isEnabled` from `Locator.IsEnabled`.
* Adds `locator.IsEnabled` and a test.
* Refactors the locator state tests.
* Removes applying slow motion in the `Frame.IsEnabled` as discussed in #234.
=> Add locator.isEnabled

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
This PR closes #347.
* Extracts `Frame.isDisabled` from `Frame.IsDisabled` so that we can use `isDisabled` from `Locator.IsDisabled`.
* Adds `locator.IsDisabled` and a test.
* Removes applying slow motion in the `Frame.IsDisabled` as discussed in #234.
=> Add locator.isDisabled

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
This PR closes #351.
* Extracts `Frame.isVisible` from `Frame.IsVisible` so that we can use `isVisible` from `Locator.IsVisible`.
* Adds `locator.IsVisible` and a test.
* Removes applying slow motion in the `Frame.IsVisible` as discussed in #234.
=> Add locator.isVisible

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
This PR closes #350.
* Extracts `Frame.isHidden` from `Frame.IsHidden` so that we can use `isHidden` from `Locator.IsHidden`.
* Adds `locator.IsHidden` and a test.
* Removes applying slow motion in the `Frame.IsHidden` as discussed in #234.
=> Add locator. isHidden

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
* Extracts `Frame.focus` from `Frame.Focus` so that we can use `focus` from `Locator.Focus`.
* Adds `locator.Focus` and a test.
Closes #339.
=> Add locator.focus

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
* Extracts `Frame.fill` from `Frame.Fill` so that we can use `fill` from `Locator.Fill`.
* Adds `locator.Fill` and a test.
Closes #338.
=> Add locator.fill

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
* Extracts `Frame.getAttribute` from `Frame.GetAttribute` so that we can use `getAttribute` from `Locator.GetAttribute`.
* Adds `locator.GetAttribute` and a test.
Closes #341
=> Add locator.getAttribute

api/locator.go, common/frame.go, common/js_handle.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
In this PR, I introduced an unexported new interface called `jsHandle` that wraps the existing public interface `api.JSHandle`. The reason is that `JSHandle`'s `Dispose` and `GetProperties` methods can panic.
Since we're aiming to separate the JS layer from the actual logic as discussed in #271, I needed to make their unexported variants return errors instead of panicking. Please let me know if there is a better way.
Besides that, the test does not try to verify the `SelectOption` from all aspects because it should be the `ElementHandle` test's job. Here, we only verify whether it routes the locator call to the `Frame`.
Closes #353.
=> Add locator.selectOption

api/locator.go, common/element_handle.go, common/element_handle_options.go, common/frame.go, common/frame_options.go, common/helpers.go, common/locator.go, examples/fillform.js, tests/locator_test.go
The `Frame` and `ElementHandle` refactoring for this feature took a little more time. It's because `Frame` and `ElementHandle` were using `DblClickOptions` instead of `DispatchEventOptions`. Please see the commits for more details.
I tested `dispatchEvent` by dispatching a click event in the `example/fillform.js` instead of calling `click`, and it worked. 
However, `Frame` and `ElementHandle` should have proper dispatch event tests in the future. The locator test only tests whether we can route the `dispatchEvent` call to `Frame`, and it does not test the event dispatching behavior to the full extent.
_PS: I forgot to name the branch `feat/335-locator-dispatchEvent` 🤦_
Closes #335.
=> Add locator.dispatchEvent

chromium/browser_type.go, common/browser.go, common/browser_process.go, common/browser_test.go
Browser doesn't own or should really care about the cleanup of the temp
dir. For now we want to avoid using cleanupFunc, but still call cleanup
from Browser.
Closes: #402
=> Refactor cleanup temp dir to remove cleanupFunc

common/helpers.go, tests/page_test.go
Before this fix, we couldn't detect the timeouts properly (v0.3.0~now). For example, in the following test, we assert that the result of the `TextContent` method is empty even if the element we're looking for does not exist. The frame action should have timed out instead of returning an empty string (`p` tag doesn't exist in `sampleHTML`).
See the `err_wrong_selector` subtest.
https://github.com/grafana/xk6-browser/blob/eeab22ebfdc5c6d2863eab9a744ea1205d6d9309/tests/page_test.go#L256-L289
This PR fixes the problem and detects the timeout error properly by using `context.DeadlineExceeded` instead of `context.Canceled`. The current system is still unstable because this fix re-surfaced a data race bug that happens from time to time (happens on frame navigation). Previously reported on #254's …
=> Fix timeout detection (callApiWithTimeout)

README.md, examples/locator.js, examples/locator_pom.js
This PR updates README for the Locator API and verifies the locator API behavior across frame navigations.
* Adds Locator API examples (`examples/`)
* Locator page object model example
* Locator across frame navigations example
* Updates the missing functionality table (README)
* Add Locator API examples (README)
The Locator API  works across frame navigations. The only place where it won't work is if the underlying frame somehow gets changed (rare?).
=> Locator API examples + validation of across frame navigations behavior

common/browser_test.go, common/element_handle.go, common/frame.go, common/frame_session.go, common/helpers.go, common/page.go, common/page_test.go, common/screenshotter.go, tests/element_handle_test.go, tests/page_test.go, tests/test_browser.go
This commit properly type-asserts to remove `nolint:forcetypeassert` directives both from the code and tests.
There are new helpers to reduce code bloat and possible error messages refactoring work:
+ `asGojaValue(v)`: returns `v` as a `goja` value or panics.
+ `gojaValueToString(v)`: returns `v` as `string` or panics.
Fixes: #417
Related: #58
=> Fix type assertions and remove nolint directives for good

tests/locator_test.go
Fixes the navigation path in tests from `//locators.html` to `/locators.html`.
=> Fix Locators test for navigation

.golangci.yml, tests/browser_test.go, tests/page_test.go
We decided to disable the wrapcheck linter for tests. This PR does that and removes `fmt.Errorf("%w", err)` from tests.
=> Disable wrapcheck linter in tests and refactor tests

.golangci.yml, common/browser.go, k6ext/k6test/vu.go, k6ext/promise.go, tests/browser_test.go, tests/test_browser.go
This PR closes #463.
* `k6ext.Promise` makes it easier to work with promisified code.
* `k6ext.AbortingPromise` is like `Promise`, allowing the event loop's abortion.
* `VU.RunLoop` makes it easier to run an event loop.
* `testBrowser.await` is a convenience function for `VU.RunLoop`. Awaits the given function until the event loop returns.
* `testBrowser.runString` makes it easy to run strings with a `fmt.Sprintf` like behavior.
An example of refactoring can be seen in `Browser.on` and its tests.
=> Add helpers for Async APIs

common/frame_manager.go, common/helpers.go, common/network_manager.go, common/page.go, common/request.go, tests/page_test.go
This fixes the most common race condition and reason for flaky tests we've seen in CI for a while now. See the example in #427 and the commits for details.
I stress tested `TestPageGoto` in CI with [this script](https://dave.cheney.net/2013/06/19/stress-test-your-go-packages) before and after these changes. Before, it would fail with the familiar 30s timeout a few minutes into the test (see jobs [#1191](https://github.com/grafana/xk6-browser/actions/runs/2795113893), [#1192](https://github.com/grafana/xk6-browser/actions/runs/2795199585), [#1193](https://github.com/grafana/xk6-browser/actions/runs/2795217065)). After the changes, the stress test ran for an hour before I stopped it (jobs [#1190](https://github.com/grafana/xk6-browser/actions/runs/2791086400), …
=> Fix `Page.goto()` race condition

common/frame_manager.go
This refactors `waitForFrameNavigation` in a similar way as `NavigateFrame` was in #480. Namely to setup the lifecycle event waiter ASAP, ~and to not call `hasSubtreeLifecycleEventFired()` which is buggy/racy itself, and not necessary.~ While I've found that calling `hasSubtreeLifecycleEventFired()` is not necessary, I decided to bring it back since I noticed some timeouts without it. It's difficult to say whether this was related, but we can leave it and remove it later if it's found to be a problem.
Fixes #498
=> Fix nil panic race in `FrameManager.waitForFrameNavigation`

examples/fillform.js
This ensures we use `Promise.all()` wherever `click()`/`waitForNavigation()` is used, which is also [suggested by Playwright](https://playwright.dev/docs/api/class-page#page-wait-for-navigation) to avoid a race condition.
And also change the example to use the Locator API, which handles navigations better.
From my local and Cloud tests, this helped resolve the errors in #495.
=> Make `fillform.js` example less racy

main.go
The k6-agent will only forward env vars to the k6 binary that start
with K6_. To be able to use pprof in the cloud environment we need
to change the env var from XK6_BROWSER_PPROF to K6_BROWSER_PPROF.
=> Fix XK6_BROWSER_PPROF env var for cloud support

common/frame.go
This is a functional change from before, since the iteration won't be interrupted by a timeout error anymore, and the promise will be rejected instead. This might be an acceptable tradeoff for using a lock, but it would be better if there was a way of interrupting the iteration if the promise is rejected.
Fixes #506
=> Fix concurrent usage of goja.Runtime in waitForNavigation

main.go
Closes #485 
This also exposes the xk6-browser version to JS scripts, which is useful for troubleshooting user scripts until https://github.com/grafana/k6/issues/1741 is implemented.
=> Export Chromium `BrowserType` implementation directly

chromium/browser_type.go, main.go, tests/test_browser.go
This was a regression introduced by #515, caused by the fact [the VU context changes after each iteration](https://github.com/grafana/k6/blob/e09bb87277865d668586429eee97158fbbfc58e5/js/runner.go#L710), so our context initialization needs to happen on each iteration (`launch()` call) as well.
I wanted to add an E2E test to cover this scenario and test multiple iterations, but the process still exits with 0 when this was broken, so we wouldn't have seen it in CI anyway. I'm not sure how to test it otherwise. We should probably dump the summary results and check them in the job, similar to [the way the test-xk6 workflow works in the k6 repo](https://github.com/grafana/k6/blob/master/.github/workflows/xk6.yml#L69-L73). But we can do that later and I didn't want to delay the fix.
=> Fix context canceled error when running more than 1 iteration

common/element_handle.go, tests/element_handle_test.go, tests/frame_test.go, tests/locator_test.go, tests/page_test.go
`ElementHandle`, `Page`, `Locator` and `Frame` all implement the `Press` method. In a recent fix (#326) combo keys with the `Shift` modifier key was fixed for the `Keyboard` `Press` method. The `Press` methods for the other classes should have worked with combo key presses, but didn't, which resulted in an error: `ERRO[0002] pressing "Shift+KeyH+i" on "#text1": key down: "Shift+KeyH+i" is not a valid key for layout "us"`. This fix will ensure that combo key presses work for all of them. This fix matches the behaviour in playwright.
Playwright test:
```js
const { test, chromium } = require('@playwright/test');
test.describe('editing', () => {
test('frame press', async () => {
const browser = await chromium.launch({ headless: false, slowMo: 500 });
const ctx = await browser.newContext(); …
```
=> Fix press in classes to work with combo keys

main.go, release notes/v0.5.0.md
This contains the release notes for v0.5.0. The main changes are acount
stability, asynchronous changes to click and waitForNavigation, and
exporting a new BrowserType, Chromium, that replaces the launch
function to launch a new chromium browser instance.
=> Release notes v0.5.0

examples/multiple-scenario.js
This PR adds a new test to demo how xk6-browser can be used together with k6. This includes:
- creating multiple scenarios where each scenario executes a different function
- different executor used for each scenario
- use of thresholds
=> add example on how to use xk6-browser with k6

common/page.go
`Page` now reads the frame url using the mutex protected method `URL()` instead of accessing the url field directly.
This was preventing us to test the locator tests in parallel. This might also help testing other tests in parallel.
Fixes: #530
=> Fix data race in frame url while logging

tests/locator_test.go, tests/static/locators.html
The `dblclick` test was wrong. It was listening for the `click` event instead of the `dblclick` event.
And the other tests were wrong too. We missed preventing capturing the loop variables in parallel tests in #389. So we weren't testing the existing locator features so far. The `dblclick` test started to fail when I fix the locator tests (so I fixed it afterward).
Somewhat related: #469
=> Fix parallel locator tests

common/frame.go
In `waitForExecutionContext` it is using a for loop to wait for the context to be set. `NewTimer` only fires once, and if the context isn't set it will deadlock. Changed to working with `NewTicker` so that it can periodically check to see if the context has been set.
=> Fix waitForExecutionContext with NewTicker

common/browser_process.go, common/browser_test.go, common/frame.go
This was leaving hanging goroutines all over the place. 
Not certain whether any of those are relevant for real running, but in tests it was both making stack traces harder to read (as you have a bunch of blocked goroutines), but it also likely was taking some CPU/MEM away from tests. The later likely isn't all that much, but still better to not have goroutines that hang around forever ;)
=> Take context Done into considerations in a bunch of places

chromium/browser_type.go, common/browser.go, common/browser_process.go, common/connection.go
This was initially an effort for #510, but since that became difficult to reproduce even in EC2, it pivoted to fixing #232 and some related issues.
See the commits for details, but in summary, this:
- Ensures we wait for the browser process to exit before ending the iteration.
Previously, we would cancel the browser context prematurely, which caused `process with PID 282373 unexpectedly ended: signal: killed` errors.
Now, we wait for the browser process to exit on its own, since the CDP `Browser.close` command does that implicitly, and only forcefully kill it if it exceeds a specific timeout (1s).
- Fixes, or rather _hides_, the `close 1006 (abnormal closure): unexpected EOF` error from #232.
See, Chrom{e,ium} doesn't close the WS connection cleanly (they don't send a [Close control …
=> Improve handling of browser process exit and WS connection closing

Dockerfile, README.md, docker-compose.yaml
Add the Docerfile, docker-compose to provide the possibility of running examples inside the docker.
Docker is the easiest way to improve the developer's UX.
=> Docker example

common/network_manager.go, common/request.go, common/request_test.go
Using a relatively long list of primitive types makes it hard to initialize `Request` and can bring uninvited bugs. I noticed this when testing `Request`/`Response` metric emissions for Issue #533. I needed to pass `nil` and false values for unwanted fields:
```go
req, err := NewRequest(vu.Context(), evt, nil, nil, "intercept", false)
```
Now:
```go
req, err := NewRequest(vu.Context(), NewRequestParams{
event:          evt,
interceptionID: "intercept",
})
```
I'm using this approach in #551 and will keep doing so if this PR is accepted.
=> Refactor to NewRequestParams

README.md, TROUBLESHOOTING.md
This is part of what we discussed in https://github.com/grafana/xk6-browser/issues/491#issuecomment-1266984454.
It will also have to be part of k6-docs, but I figured we might want to start it here. How great it would be if the docs were only in this repo and https://k6.io/docs/ would be built from them... :thought_balloon::pray:
It would also be great if all of these documents, like SUPPORT.md, CONTRIBUTING.md and the inline examples were in a `/docs` subdirectory, to avoid cluttering the repo root and make the README shorter. See [how Puppeteer structures this](https://github.com/puppeteer/puppeteer/tree/main/docs). But we can tackle this later.
This is not an exhaustive list of common issues, and we should integrate the `command not found` issue we mention on the [front …
=> Add troubleshooting document

common/event_emitter.go, common/event_emitter_test.go
Events are sometimes out of order due to use using a goroutine to publish events to the handler concurrently as there's no guarantee when the goroutines will run (the first goroutine to be created isn't necessarily going to be the first to run). To overcome this, a `queue` has been added per handler to synchronise all publishes of events to that handler as well as a `mutex` so that only one `emitEvent` goroutine can read from the `queue` **and** write to the handler's channel at any one time.
We tried working with a buffered channel instead of a `queue` (which is a slice). Unfortunately it's difficult to determine how large the channel needs to be to work with the test -- the more complex the test, the more events that will be emitted. For now we think it is easier to work with a `queue` …
=> Add a queue per handler to keep events in order

common/network_manager.go, common/network_manager_test.go, common/request.go, common/response.go, k6ext/k6test/vu.go
Please take a look at Issue #533 to see my findings and why I wanted to use walltime here.
* **Test runs on staging**: Before the fix -> `141373`, After the fix -> `141372`.
* I can move `AssertSamples` and expose VU samples in separate PRs, please let me know.
* I put the request/response timing skew issue in a single test. Again, please let me know if you want me to separate them.
---
Closes #533.
=> Fix #533 wrong metric sample pushed to cloud

api/browser_context.go, api/browser_type.go, api/element_handle.go, api/frame.go, api/page.go, api/response.go, chromium/browser_type.go, common/browser_context.go, common/element_handle.go, common/frame.go, common/page.go, common/response.go
=> Move all not implemented APIs to return promises

common/frame_session.go, common/network_manager.go
There is no locking around the `state.Group` and it is modified by calls to `group()` while on the event loop. So for the time being to modify it - it is needed to be on the event loop.
Also the adding of the tag isn't needed as that is done automatically by `group()`
=> Fix races around touching state.Group outside of the event loop

common/frame.go, common/frame_options.go, common/frame_session.go, common/page_options.go, tests/frame_test.go, tests/static/prolonged_network_idle.html, tests/static/prolonged_network_idle_10.html
Fixes: https://github.com/grafana/xk6-browser/issues/597
There are three `lifecycle` types that are emitted from the browser over CDP:
- `load`
- `DOMContentLoaded`
- `networkIdle`
We should be able to to wait on any of these and proceed with the test once we receive them and action on them at an appropriate time. Currently (4485c6d0caf9276b3a772e708a23f526a23f665c) the wait for `networkIdle` waits indefinitely on some websites e.g. google.com.
IMO, we should be able to rely on the browser to send us the CDP lifecycle events, which in my tests it does do. What we seem to have (and I can only guess the reasoning behind it) are three redundancies in place incase we don't receive these events from the browser at all or within a set timeout (the timeout scenario is only for `networkIdle`) or …
=> Fix wait for networkIdle lifecycle event

chromium/browser_type.go, common/context.go, common/helpers_test.go, common/network_manager.go, common/network_manager_test.go, common/response.go, log/logger.go, tests/browser_test.go
This adds an `iteration_id` field to all log events that uniquely identifies a k6 iteration, and thus a single browser start/stop cycle. I'm finding it relatively useful when testing issues like #566 that only happen when stress testing the entire `tests` package, and not a single test in isolation, since I can filter log events for a specific iteration.
It's only added to events when `XK6_BROWSER_LOG` is set to `debug` or `trace`.
Related to #422
=> Add iteration ID field to log events

tests/page_test.go
This PR is a demonstration of a simple optimization and its effects.
`TestPageScreenshotFullpage` is the slowest test we have (see #612). So it's a low-hanging fruit to optimize. A quick fix sped up the test by 35% on my machine.
```
Before: 671259438 ns/op 43410268 B/op 8771 allocs/op
After : 363529042 ns/op  5970741 B/op 8533 allocs/op
```
Updates #612
=> Optimize TestPageScreenshotFullpage

common/browser.go, common/browser_process.go
This reverts commit e35e88c949757d56b707d88ad0f4e749f44352d8.
It seems the previous change might've been causing some flakiness issues. See https://github.com/grafana/xk6-browser/issues/566#issuecomment-1285672600 and https://github.com/grafana/xk6-browser/pull/598#issuecomment-1285750715 .
Using a context instead of a channel was cleaner, and while on the surface shouldn't have any functional differences, the context cancellation might be time sensitive, so a channel should be safer.
=> Revert "Use context cancellation for signaling that browser process is done"

common/browser_options.go, common/browser_options_test.go
Fixes #407 by ignoring **any options** with `null` or `undefined` values given by a test script.
For example:
* Setting `executablePath` to `null` will be ignored, and its default value will be used.
* Or, setting `headless` to `undefined` will be ignored, and `headless` will stay as `true` ([its default value](https://github.com/grafana/xk6-browser/blob/4a47b35e132d6d188e80c7543686c3665f4c942b/common/browser_options.go#L46)).
* Setting `args` to `null` will be ignored, and `args` will stay `nil` (its default).
---
WDYT about returning an error when an option is set to `null` or `undefined`?
**Current approach.**
* Pros: Allows defaults to be used when one of the options is set to `null`. This can also be a double-edged sword (cons-es below). Slightly faster parsing (since it skips the …
=> Browser should not override defaults with null values

chromium/browser_type.go, common/browser_options.go, common/browser_options_test.go, common/browser_test.go, common/helpers_test.go, common/network_manager.go, common/network_manager_test.go, common/response.go, log/logger.go
It logs when one of the default browser launch options is set to either `null` or `undefined` and overridden by its default option. I needed to move `makeLogger` from `launch` to `Launch` so we could log something in `BrowserType.Launch`.
Currently, `Parse` doesn't mind the `logCategoryFilter` and `debug` options. There was a chicken-egg situation: `Parse` needs a logger, but we don't know about the `logCategoryFilter` and `debug` options until `Parse` finishes. And, `Parse` needs to log!
This should [allow](https://github.com/grafana/xk6-browser/pull/608#discussion_r1008050172) merging #608 and #619.
PS: I can squash this after the review if you want.
=> Log when a launch option is set to null

common/browser_process.go, common/browser_process_test.go
This ensures we don't return on the first error we see, since they could be non-fatal, but actually wait for the browser process to exit. I confirmed this fixed the issue locally for me with the `dbus` errors mentioned in #614, and I added some unit tests for `parseDevToolsURL()`.
It's based on #599, since it needed to also check if the process ended unexpectedly, and that was safer with the channel approach. So let's merge that first.
Fixes #614
=> Wait for browser process to exit before returning first error from stderr

examples/browser_args.js
On mac using 127.0.0.254 doesn't seem to work, whereas 127.0.0.1 does work in the way this test intends it to work.
=> Fix the ip address in browser_args

common/frame.go, common/frame_manager.go
Two race conditions were found while stress testing some lifecycle event tests. The resulting log is:
```
WARNING: DATA RACE
Read at 0x00c0008f9328 by goroutine 254:
github.com/grafana/xk6-browser/common.(*FrameManager).requestFailed()
/Users/ankuragarwal/go/src/github.com/grafana/xk6-browser/common/frame_manager.go:449 +0x2cc
github.com/grafana/xk6-browser/common.(*NetworkManager).onLoadingFailed()
/Users/ankuragarwal/go/src/github.com/grafana/xk6-browser/common/network_manager.go:357 +0x234
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents()
/Users/ankuragarwal/go/src/github.com/grafana/xk6-browser/common/network_manager.go:330 +0x144
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
/Users/ankuragarwal/go/src/github.com/grafana/xk6-browser/com …
```
=> Add mutex to prevent data race on pendingDoc and use mutex when reading frame.inflightRequests

common/page.go, tests/frame_test.go, tests/lifecycle_wait_test.go, tests/static/prolonged_network_idle.html, tests/static/prolonged_network_idle_10.html, tests/static/reload_lifecycle.html
Closes: https://github.com/grafana/xk6-browser/issues/622
The logic to `waitUntil` has been copied from `FrameManager.NavigateFrame`. The issue was that `waitUntil` when used with `networkIdle` wasn't working as expected -- the wait would end too early.
I've also refactored the previous lifecycle event tests into a new file. There will be a lot more lifecycle event tests coming in future PRs, so it's best to keep them all in one place.
=> Fix waituntil for page.reload

common/frame.go, common/helpers.go, tests/lifecycle_wait_test.go, tests/page_test.go, tests/static/wait_for_nav_lifecycle.html
This PR was opened to help in part with issue https://github.com/grafana/xk6-browser/issues/593.
This PR's aim is to do two things:
1. Add missing tests for `WaitForLoadState` when using `waitUntil` options.
2. Fix an issue where `WaitForLoadState` needs to wait for new events from the browser.
https://github.com/grafana/xk6-browser/pull/623 needs to be merged into `main` first before this PR.
The tests all follow a similar setup to what is already present in `main` and in https://github.com/grafana/xk6-browser/pull/623.
The fix involved copying the `waitUntil` logic used in [FrameManager.NavigateFrame](https://github.com/grafana/xk6-browser/blob/main/common/frame_manager.go#L578).
=> Fix WaitForLoadState and add tests

Dockerfile
Removing the fixed version of the chromium because it's not available in the repositories after a while. 
It was reported in [community forums](https://community.k6.io/t/issue-with-building-xk6-browser-as-docker-image/5109). 
```
$ docker-compose build --no-cache xk6-browser
....
Step 5/9 : ARG CHROMIUM_VERSION=106.0.5249.61-1~deb11u1
---> Running in bc2110352dd6
Removing intermediate container bc2110352dd6
---> 5b4bee2c903b
Step 6/9 : RUN apt-get update &&     apt-get install -y chromium=${CHROMIUM_VERSION}
---> Running in 3537960e2093
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian …
```
=> chore: remove static chromium version

tests/browser_test.go
This race condition was found in a [CI job ](https://github.com/grafana/xk6-browser/actions/runs/3395754810/jobs/5646033469)which failed.
```
==================
WARNING: DATA RACE
Read at 0x00c001048490 by goroutine 161:
github.com/grafana/xk6-browser/tests.TestBrowserLogIterationID()
/home/runner/work/xk6-browser/xk6-browser/tests/browser_test.go:170 +0x176
testing.tRunner()
/opt/hostedtoolcache/go/1.18.8/x64/src/testing/testing.go:1439 +0x213
testing.(*T).Run.func1()
/opt/hostedtoolcache/go/1.18.8/x64/src/testing/testing.go:[148](https://github.com/grafana/xk6-browser/actions/runs/3395754810/jobs/5646033469#step:5:149)6 +0x47
Previous write at 0x00c001048490 by goroutine 14:
github.com/grafana/xk6-browser/tests.(*logCache).Fire() …
```
=> Fix a race condition with logCache.entries

chromium/browser_type.go, common/browser_options.go, common/browser_options_test.go, common/browser_test.go, go.mod, go.sum, k6ext/cloud.go, k6ext/doc.go
This PR ignores cloud-only options and logs a message when xk6-browser is running in the cloud.
The cloud-only options are: `devtools`, `executablePath`, and `headless`.
* The `k6ext.OnCloud` detects the cloud run and returns `true` if the [`K6_CLOUDRUN_INSTANCE_ID`](https://k6.io/docs/cloud/creating-and-running-a-test/cloud-tests-from-the-cli/#cloud-environment-variables) environment variable exists.
* `LaunchOptions.Parse` ignores the cloud-only options if we're running in the cloud.
Closes #414.
=> Force browser opts in cloud

common/frame.go
executionContextMu isn't needed to be locked and unlocked in this (WaitForFunction) method as it doesn't r/w to executionContext or documentHandle. This function later calls an unexported method with the same name, which does require access to executionContext.
A deadlock was occurring later in waitForExecutionContext since this method was holding on to the lock.
Closes: https://github.com/grafana/xk6-browser/issues/635
=> Fix deadlock with executionContextMu

release notes/v0.6.0.md
This contains the release notes for v0.6.0. We've primarily worked on making xk6-browser more stable. There are many bug fixes which users may or may not have run into, but we did while we were testing the application. `page.goto` is no async, which is a breaking change.
=> Release notes v0.6.0

README.md
Update demo video to show that `page.goto` is now async
=> chore: update xk6-browser demo video

common/frame_session.go, tests/frame_test.go, tests/static/dialog.html
Partly closes: https://github.com/grafana/xk6-browser/issues/655
We have had a feature request recently as well as seen dialog boxes being used elsewhere. There currently isn't a work around to removing dialog boxes in the path of a test. This change will automatically dismiss the dialog boxes (and accept it for `beforeunload` type dialogs).
=> dismiss dialog box automatically

ROADMAP.md
The current roadmap has been created in Apr'22 and since then the project has advanced quite significantly. Proposed changes are reflecting current project state and the ongoing development.
=> Update project roadmap

browser/module.go, go.mod, go.sum, release notes/v0.7.0.md
=> Release v0.7.0

.github/workflows/test.yml
This job will test xk6-browser against the latest version of k6 from master. We should be able to catch breaking changes earlier during the cycle so that we're not rushing to fix them just before the release.
closes: https://github.com/grafana/xk6-browser/issues/659
=> Add a CI job to test against the latest k6

browser/mapping.go, browser/mapping_test.go, browser/module.go, browser/module_test.go
Exposing VU is preliminary for using promises in the mapping layer.
Normally [this code](https://github.com/grafana/xk6-browser/blob/update/697-js-examples-to-async/chromium/browser_type.go#L112) loads the VU so that the code in the `common` package can call [k6ext/promise](https://github.com/grafana/xk6-browser/blob/a11233766d5580b5ba8cf1ed5b7b9bb4dcfd8f66/k6ext/promise.go#L34-L39).
Since we're moving the promise handling to the mapping layer (#683), the mapping layer needs a VU from the context to pass it to the `k6ext.Promise()`.
`k6ext.Promise()` gets the current VU from the context:
https://github.com/grafana/xk6-browser/blob/a11233766d5580b5ba8cf1ed5b7b9bb4dcfd8f66/k6ext/promise.go#L34-L39
So, in the mapping layer, we need to inject VU into the context:
```go
func (*RootModule) …
```
=> Expose VU to the mapping layer

tests/lifecycle_wait_test.go
So far, we haven't been testing the lifecycle tests. The test variables were captured because `t.Parallel`. This fixes it.
Related: #647, #644, #643
=> Fix lifecycle tests parallelism bug

tests/frame_test.go
Another test parallelism bug.
Related: #663
=> Fix dismiss dialog test bug

common/frame_manager.go
Returning an interface makes the `response` never `nil`. This creates problems when we want to check whether the `response` is `nil` or not.
Here, it never becomes `nil` even if it happens to be `nil`:
https://github.com/grafana/xk6-browser/blob/f2e001837a6b426fba95c873d4f97b3378da5d94/common/frame_manager.go#L644-L666
So we can't check whether it's `nil` or not here:
https://github.com/grafana/xk6-browser/blob/d2785768849aa7cc976eba27cb983cf2dd1475af/browser/mapping.go#L99-L102
=> Fix frame manager navigate frame bug

api/frame.go, api/page.go, browser/mapping.go, common/frame.go, common/page.go, tests/browser_context_options_test.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/frame_test.go, tests/lifecycle_wait_test.go, tests/locator_test.go, tests/network_manager_test.go, tests/page_test.go
This PR removes the promise handling from the `Goto` methods and moves the handling to the mapping layer. Sorry, the PR is pretty big. It wasn't possible to split it into more commits without breaking tests. I hope you'll be able to review it. One tip is to review each file from the `Files changed` tab with the file navigation on. Depends on your preference. Feel free to let me know if you have any questions.
PS: I kept the fixup commits for your convenience. I'll squash them all when you finish reviewing. That's why it's not in the "ready for review" yet; still a draft.
Closes #705. Updates #683.
=> Map [Page|Frame].Goto promises and fix tests

go.mod, go.sum, tests/test_browser.go
As explained [in this commit](https://github.com/grafana/xk6-browser/pull/715/commits/0f65c790730f57d21a5a9cd9050bc1c1309b2262), this helper will help when we're executing multiple goroutines: Imitating promise-like behavior. For example, `waitForNavigation` and `click` will need this helper to execute in parallel and give us an `error` or `nil`.
=> Add a testbrowser function runner helper

api/frame.go, api/page.go, browser/mapping.go, common/frame.go, common/page.go, tests/frame_manager_test.go, tests/lifecycle_wait_test.go, tests/page_test.go
This moves the promise handling for [Page|Frame].WaitForNavigation to the mapping layer. The lifecycle tests are still using promises since its logic is complex to figure out for now. We should refactor them when we finish—I've added a task on #683.
Related: #683 
Closes: #706
=> Map [Page|Frame].WaitForNavigation and fix tests

api/frame.go, api/page.go, browser/mapping.go, common/frame.go, common/page.go, tests/page_test.go
The tests still need some refactoring, but it's out of focus for this PR. I tried to make them pass without changing things much.
Ideally, these tests should be written by the JavaScript side (as we'll do in #675). They are entirely concerned about the JS side of things, and these Go tests become futile, complicated, and hard to understand and maintain.
Closes #708. Updates #683.
=> Map [Page|Frame].WaitForFunction promises and fix tests

api/browser.go, browser/mapping.go, common/browser.go, tests/browser_test.go, tests/network_manager_test.go
This moves the promise handling of `Browser.on` to the mapping layer.
Ideally, a test should be written by the JavaScript side. See issue #675 for details. The reason is, they are completely concerned about the JS-side of things and the Go tests become futile, complicated and hard to understand.
Closes https://github.com/grafana/xk6-browser/issues/709. Updates https://github.com/grafana/xk6-browser/issues/683.
=> Map Browser.On and fix test

tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go, tests/test_browser.go
Now that promises have been moved to a level above the business logic, we can remove the need to run things in promises and assume (in most cases) that things will run synchronously. Where there's still a need to run things in parallel we can use the run method on testBrowser.
Updates https://github.com/grafana/xk6-browser/issues/683.
=> Remove await method from testBrowser

.github/workflows/e2e.yml, .github/workflows/test.yml
This PR modifies the `e2e` and `test` GH actions in order to trigger their execution on a daily basis. The motivation for this is to increase the feedback loop for possible braking changes due to modifications done in k6 core.
Closes #701.
=> Run test and e2e CI actions daily

common/browser_options.go, common/remote_object.go, common/remote_object_test.go, go.mod, go.sum, log/logger.go
This PR tries to get rid of some dependencies currently required by the main module that are marginally used. More specifically:
- Removes the usage of `github.com/fatih/color`
- Removes the requirement for `golang.org/x/exp` from main module (still required as transitive)
This produces the direct inclusion of `github.com/google/go-cmp` but that is only used inside `tests` pkg
- Replaces the usage of `github.com/hashicorp/go-multierror` with a custom implementation that fulfills our current use case
Closes #729.
=> Reduce dependencies

common/browser_process.go
When the browser fails to load prior to xk6-browser connecting to it via CDP, then we need to make it clear what's happened.
Partially Resolves: https://github.com/grafana/xk6-browser/issues/648
=> Update the message when browser failed to load

browser/module.go, browser/module_test.go
We have decided that after the merge k6 will take control of restricting test runs, allowing current browser test users to not be affected (for now).
=> Revert env var that disables test runs

browser/module.go, release notes/v0.8.0.md
=> Release v0.8.0

api/browser_context.go, api/browser_type.go, api/element_handle.go, api/frame.go, api/page.go, api/response.go, chromium/browser_type.go, common/browser_context.go, common/element_handle.go, common/frame.go, common/page.go, common/response.go
This is a continuation of the efforts set in #683. Handling the Async APIs in the mapping layer. Please take a look at issue #742 for more details. This can also help the work in #688—where we need to remove the promises and return errors 🤔?
Closes #742
=> Remove Async handling from the core methods

CONTRIBUTING.md, Makefile, SECURITY.md
I noticed we didn't have any guidelines on how to contribute after I saw a comment on one of the issues.
These guidelines will guide external contributors on how to contribute to the project. It also adds a makefile to make it easier for external contributors to ensure their changes meet a set standard.
=> Add contributing guidelines for external use

browser/mapping.go, browser/mapping_test.go, browser/module.go
The initial context that we get from the vu in NewModuleInstance should not be cached since the context is closed per iteration. The best practice is to work with the context directly from vu when it's needed.
This became apparent when the initial context was used in a test API method (`Launch`) and the test was failing with `context canceled`.
Related: #704 #702 #673 #744
=> Fix to use a fresh VU context on each mapped method call

common/page.go, tests/page_test.go
The problem was present in the way frame.Evaluate method was called underneath, as it currently only supports executing callable functions. The fix mimics the implementation currently in place for page.Title() method.
Closes #748 .
=> Fix page.URL() method

common/browser.go
The `closing` state is not needed:
1. Nothing else relies on the `closing` state.
2. Straight after `closing` is set, `closed` is set.
We still need the `closed` state as there is code that changes behaviour if the state is no longer `open`.
=> Remove the browser closing state

common/frame.go, tests/frame_test.go
The problem was present in the way frame.Evaluate method was called underneath, as it currently only supports executing callable functions.
Closes #756.
=> Fix Frame.Title() method

browser/module.go, release notes/v0.8.1.md
=> Release v0.8.1

browser/mapping.go, browser/mapping_test.go
We shouldn't expose some of the methods as they are internal to the extension, have no meaning for the users, and Playwright doesn't support them.
Refactoring to the tests should be done with the fix together so as not to break the tests. Some parts could be in another commit, but the commit itself is short enough anyway.
Updates: #784
=> Fix unmap internal methods

api/browser_type.go, browser/mapping.go, browser/mapping_test.go, browser/module.go, browser/modulevu.go, browser/pidregistry.go, chromium/browser_type.go, k6ext/context.go, k6ext/panic.go, tests/browser_test.go, tests/test_browser.go
I'm strongly against exposing global variables as we did in #762 and #755 😒😭 
Our goal was to _fix_ [the regression](https://github.com/grafana/xk6-browser/pull/744#issuecomment-1418901227), preserve the v0.8.0 behavior, and move on with #744 as we [discussed](https://github.com/grafana/xk6-browser/pull/744#issuecomment-1418986802).
However, we ended up going with #762 and #755 instead and fixed another problem: a multi-browser close issue when one of them panics in the same script (_note that nobody has reported such a problem and usage so far_). While the PRs did fix the multi-browser close issue, they introduced global variables 😒
I'm so grateful for your (@ankur22) contributions to that effort! 🙇 I believe we can do better than relying on global variables. That's not the best solution …
=> Clear zombie browser processes on panic

browser/modulevu.go
Fixes a tiny but important regression in #779.
We should put the VU with `pidRegistry` into the `Context` so the panicking goroutines can grab it.
=> Fix multi browser close vu was missing in Context

api/browser_context.go, browser/mapping.go, common/browser_context.go, k6error/internal.go
At the moment the codebase uses panic too liberally and we don't have control over when we actually want to abort all test runs vs when we only want to fail the current test iteration.
The idea is that we will bubble up errors all the way to the mapping layer, where it can decide on whether to panic or to return an error to goja.
This would mean that we have more control over when to panic, and to be more aware of what we want to panic on, as well as using good GO error handling practices throughout the codebase.
This is the first PR that demonstrates how we can catch internal errors. There is another PR where we had most of the discussion and several other issues were found and resolved ([#744](https://github.com/grafana/xk6-browser/pull/744)). #744 was abandoned in favour of a new PR as …
=> Return an error from BrowserContext.SetExtraHTTPHeaders and handle panic in mapping layer

browser/mapping_test.go
This test will fail if a method is mapped and not exists on the API surface (api/). The test excludes custom mappings.
Realized it we were missing this when I was working on a bug.
=> Add a testing functionality to detect redundant mappings

tests/logrus_hook.go, tests/network_manager_test.go
These helpers should help us to better see the log output locally and on CI if the test fails. I constantly needed to dump log requests when testing #687. This helper automatically does that for us.
For example, if the following fails, we have no idea why it fails unless we dump the logs by hand:
https://github.com/grafana/xk6-browser/blob/34827928fce38c3ac395b3542a3bac9f20063366/tests/network_manager_test.go#L26
Example output when we use the `assertContains` helper:
https://github.com/grafana/xk6-browser/blob/7bd82754483c8b5b3680c50c35f5cabdaf53375e/tests/network_manager_test.go#L26
```bash
=== RUN   TestURLSkipRequest
=== PAUSE TestURLSkipRequest
=== CONT  TestURLSkipRequest
network_manager_test.go:26: expected log cache to contain "skipping request handling of data URL", but it …
```
=> Add assert log contains and log dump helpers

common/browser.go, tests/browser_test.go
This PR does the following:
* Allows executing `Browser.Close` only once.
* Warns users with "a friendly message" when it's called multiple times.
Notes:
* `Close()` is thread-safe as only the same VU or testBrowser use it.
You can try the result with this script:
```js
import { chromium } from 'k6/x/browser';
const browser = chromium.launch();
const page = browser.newPage();
await page
.goto('https://test.k6.io/', { waitUntil: 'networkidle' })
.finally(() => {
page.close();
browser.close();
});
await page
.goto('https://test.k6.io/contacts.php', { waitUntil: 'networkidle' })
.finally(() => {
page.close();
browser.close();
});
}
```
It should print:
```
WARN[0002] Please call browser.close only once, and do not use the browser after calling close. …
```
=> Add browser close friendly err (#687)

api/browser_context.go, browser/mapping.go, common/browser_context.go, k6error/internal.go, k6ext/panic.go
`Fatal` better describes the error, and it will help distinguish from other internal errors (which are generally temporary). `Fatal` is a permanent error, which should end the whole test run not just the current iteration. If we ran the same iteration again then there's a 100% chance that we will run into the same error, e.g. trying to work with an unimplemented API is a `Fatal` error.
Here are two test scripts I used to test this change:
When ran with `xk6 run -i 10 examples/test.js` before the change, this test will iterate 10 times, failing each iteration. After the change it will stop on the first iteration.
```js
import { chromium } from 'k6/x/browser'
const browser = chromium.launch({headless: false})
const context = browser.newContext() …
```
=> Rename ErrInternal to ErrFatal and use abort

chromium/browser_type.go
This increases the security by default when launching chrome browser. This flag was only required when running xk6-browser as root, which mainly happened when being executed in a Docker container.
Now if xk6-browser is run as root, due to the removal of this flag, an error message like: _**"Running as root without --no-sandbox is not supported"**_. Which should be user friendly in order to understand the root cause, and the user can still force the launching with `--no-sandbox` by specifying extra browser flags as explained in `launch` method [documentation](https://k6.io/docs/javascript-api/k6-browser/api/browsertype/launch/).
Example output of running xk6-browser without `--no-sandbox` flag inside a Docker container which runs as root user.
```shell
/\      |‾‾| /‾‾/   /‾‾/   
/\  /  \ …
```
=> Remove --no-sandbox as default browser flag

api/element_handle.go, api/frame.go, api/page.go, browser/mapping.go, common/element_handle.go, common/frame.go, common/page.go, tests/element_handle_test.go, tests/keyboard_test.go, tests/page_test.go
This allows us to:
- Better handle extension errors.
- Leaves the decision of **properly handling errors** to Goja when an element is not found. This is how it's done in the k6-core and other extensions.
Returning an error from the mapping layer also allows us to prevent multiple unnecesary panics.
<details>
<summary>You can use this script to test the behavior (main and this branch)</summary>
```js
import { check } from 'k6';
import { chromium } from 'k6/x/browser';
thresholds: {
checks: ["rate==1.0"]
}
}
export default async function() {
const browser = chromium.launch({
headless: __ENV.XK6_HEADLESS ? true : false,
});
const context = browser.newContext();
const page = context.newPage();
try {
await page.goto('https://test.k6.io/');
check(page, {
'Title with CSS …
```
=> Add error handling to wildcard selectors

log/logger.go
While doing this I've also refactored the code a little bit. Let me know if you think the otherwise.
Closes: #823
=> Refactor logger.New to accept FieldLogger

api/browser.go, api/browser_context.go, api/element_handle.go, api/frame.go, api/js_handle.go, api/page.go, api/worker.go, browser/mapping.go, common/browser.go, common/browser_context.go, common/element_handle.go, common/element_handle_test.go, common/execution_context.go, common/frame.go, common/js_handle.go, common/page.go, common/worker.go, tests/browser_context_options_test.go, tests/browser_context_test.go, tests/browser_test.go, tests/element_handle_test.go, tests/js_handle_get_properties_test.go, tests/network_manager_test.go, tests/page_test.go, tests/test_browser.go
The error output is similar to #820.
Please let me know if you see other edge cases, so I can amend them.
Here are some test snippets you can try.
<details>
<summary>evaluateHandle</summary>
Output:
```
ERRO[0001] Uncaught (in promise) GoError: evaluating handle: result is nil
at github.com/grafana/xk6-browser/browser.mapPage.func2 (native)
at file:///Users/inanc/grafana/k6browser/tests/evaluate_handle.js:20:54(31)  executor=per-vu-iterations scenario=default
```
Script:
```js
await page.goto('https://test.k6.io/', { waitUntil: 'load' });
const pageTitleHandle = await page.evaluateHandle(() => {
return document.querySelector('nothing');
});
```
</details>
<details>
<summary>waitForSelector</summary>
Output:
```
ERRO[0001] Uncaught (in promise) GoError: querying selector "x"
at …
```
=> Fix Edge-case: Mapping fails if the extension code returns nil values #804

go.mod, go.sum, k6ext/k6test/vu.go
We [detected an incompatibility](https://github.com/grafana/xk6-browser/actions/runs/4434049483/attempts/2) with k6-core:
- `BPool` becomes `BufferPool` in this [PR](https://github.com/grafana/k6/pull/2879).
This PR fixes the issue.
=> Update to k6-core master and fix BPool

k6ext/panic.go
The current code returns when it can't find a process with PID, instead of trying to kill the rest. This PR fixes that sneaky bug.
Related: #779
=> Fix killing a browser process on panic if one of them is missing

common/frame_session.go, k6ext/metrics.go
We no longer need this metric for three reasons:
1. For an unknown reason Chrome doesn't always return this metric measurement. It seems that if we use slowmo, then it does appear.
2. It's being deprecated by Chrome and lighthouse as it is very inconsistent where small difference in page loads and how the browser implements the measurement all affect the end result.
3. Web vitals is almost ready and it is the industry standard way of measuring frontend performance.
Closes: https://github.com/grafana/xk6-browser/issues/837
=> Remove first meaningful paint

browser/mapping.go, browser/mapping_test.go, browser/module.go, k6ext/cloud.go, k6ext/env.go, k6ext/env_test.go, tests/browser_type_test.go, tests/test_browser_proxy.go
This PR modifies the `BrowserType.Launch` mapping function in order to transition to `BrowserType.Connect` if the browser is detected to be remote and the CDP WS URL is given by the environment. This is done to increase compatibility for using `launch` method in the JS API and transparently transition to `connect` if the browser is remotely handled and this set up is indicated by the environment.
Closes #808.
=> Transition from Browser.Launch to Browser.Connect

common/frame_session.go, k6ext/metrics.go
This is a regression. We had removed this in https://github.com/grafana/xk6-browser/pull/836, but it was accidentally added back in https://github.com/grafana/xk6-browser/pull/838.
As mentioned in https://github.com/grafana/xk6-browser/issues/831#issuecomment-1496285905, we should work with the `webvital_first_contentful_paint` instead of `browser_first_contentful_paint`.
Linked to https://github.com/grafana/xk6-browser/issues/831
=> Remove browser first contentful paint

common/remote_object.go, common/remote_object_test.go
=> Fix remote object parsing when subtype is `null`

common/frame.go, common/js/injected_script.js, common/locator.go, tests/locator_test.go, tests/static/locators.html
This PR fixes the `Locator.WaitFor` functionality when the state defined is either `hidden` or `detached`. Previously, waiting for these two states would result in an infinite pooling loop and eventually a TO error.
Besides the integration tests included in the PR, this changes can be tested also using this [test browser](https://github.com/ankur22/testserver) implemented by @ankur22 and executing the following script:
```js
import { chromium } from 'k6/x/browser'
const browser = chromium.launch({
headless: false,
})
const context = browser.newContext()
const page = context.newPage()
try {
await page.goto('http://localhost/other', { waitUntil: 'networkidle' })
page.locator("#attach-detach").waitFor({state: "detached"});
console.log("detached"); …
```
=> Fix Locator.WaitFor for `detached` and `hidden` states

common/frame.go, common/frame_session.go, examples/multiple-scenario.js, k6ext/metrics.go
Now that we have web vitals, we have evaluated the existing browser metrics:
- [browser_first_paint](https://github.com/grafana/xk6-browser/issues/831#issuecomment-1496313265)
- [browser_dom_content_loaded](https://github.com/grafana/xk6-browser/issues/831#issuecomment-1497094423)
- [browser_loaded](https://github.com/grafana/xk6-browser/issues/831#issuecomment-1497100020)
Our conclusion is that none of these metrics gives us more value or answers questions that we don't already have answers for from the web vitals. The web vitals concentrate on measuring and showing users how useable the website it, rather than these existing metrics which only show us how long it took to download the html file, it's dependencies and when the first element was rendered (usually the background colour). …
=> Remove existing browser namespaced metrics

chromium/browser_type.go, chromium/browser_type_test.go, common/browser_options.go, common/browser_options_test.go
A decision was made to no longer support the devtools browser option, which behaves as a flag in order to automatically enable DevTools in all new pages as this was not providing much value.
Closes #867.
=> Remove support for browser devtools option

chromium/browser_type.go, common/browser_options.go, common/browser_options_test.go, common/browser_process.go
A decision was made to no longer support the env browser option as this was not providing much value.
Closes #869.
=> Remove support for browser env option

common/browser_options.go, common/browser_options_test.go
A decision was made to remove proxy from browser option as, even though the option is parsed and accepted, it has no implication on the rest of the code as we are missing the actual implementation. Therefore the option will not be parsed from now on until we complete the implementation so it can have an effect on k6 browser execution.
=> Remove support for browser proxy option

common/browser.go
I suggested this earlier on to detect nil sessions. But now, this warning is outdated because when users running multiple instance/VU tests, they will see dozens/hundreds lines of warnings.
The core reason we receive a lot of these warnings is:
We need to correctly handle the CDP messages while sending and receiving them (the order of them).
https://github.com/grafana/xk6-browser/pull/848
=> Update nil session log warn to debug in page attach

chromium/browser_type.go
This PR modifies the browser launching/connecting process to not pass a context with timeout to the actual browser process cmd handle and/or implementation closing handle. Currently this was done using as timeout the value set for the browser.timeout option, which should serve a different purpose.
Instead, it makes the browser process handle and its [closing handling method](https://github.com/grafana/xk6-browser/blob/480c0c1f74ef377570be4a6a720ddd7a1cd447e7/common/browser_process.go#L64) depend on the VU context.
Closes #865.
Closes #864.
=> Disable timeout on browser process execution

tests/webvital_test.go
This returns when all the conditions are met from within the goroutine so that the expected map is not written to once the context is cancelled.
```[tasklist]
```
=> Fix race condition in web vital unit test

common/network_manager.go, common/network_manager_test.go, k6ext/metrics.go
When a request completes we want to measure how many of these failed. This is based on the status code of the response. If the code is outside of the 200-399 range, it is deemed to have failed. The default status code range was taken from k6.
The opposite is also possible to determine, we can work out which requests succeeded since the value of the metric will be 0.
We're using a custom metric named `browser_http_req_failed`, instead of the builtin k6 `http_req_failed`. There was a concern that if the browser module worked with the builtin k6 metric, then the results would be skewed for both modules and therefore meaningless. This is due to the fact that the implementation of http could differ. Users are also likely to want to understand their API http failures differently to their …
=> Add request failed metric

browser/module.go, browser/registry.go, browser/registry_test.go
`newRemoteRegistry` now needs to parse two env vars. The first is the one that we have already defined, `K6_BROWSER_WS_URL`, the new one is `K6_INSTANCE_SCENARIOS`. `K6_INSTANCE_SCENARIOS` defines a JSON object of the form:
```json
[
{
"id": "one",
"browsers": [
{ "handle": "ws://1..." }
]
},
]
```
Each scenario will generally point to a unique ws url, which is from a unique instance of chrome. Currently we are only working with chrome, and all chrome instances are setup in the same way. In the future we will want to be able to launch different chrome instances each with their own unique characteristics as well as other web browsers.
`K6_INSTANCE_SCENARIOS` takes precedence over `K6_BROWSER_WS_URL`. `K6_BROWSER_WS_URL` could still be useful for debugging purposes.
Closes: …
=> Parse the scenarios json from the `K6_INSTANCE_SCENARIOS` env var

common/frame_session.go, k6ext/metrics.go, tests/webvital_test.go
There are multiple reasons for making this change:
1. We're reducing the number of time series.
2. The rating should live as close to the value that it represents.
3. The rating in the summary is noise that doesn't add value unless we break them down by url.
4. This shouldn't increase the cardinality of the metric that we're labelling with the rating. It's a better trade off than having more time series metrics.
5. The summary at the end will be a bit more focused and shorter.
You should be able to run any example test (e.g. the fillform.js test). The web vital summary output should now look like this (note that we no longer have the rating metrics):
```bash
browser_web_vital_cls..............: avg=0.000029 min=0        med=0.000029 max=0.000057 p(90)=0.000052 p(95)=0.000055 …
```
=> Remove the web vital rate metric time series metrics

common/network_manager.go, common/network_manager_test.go, k6ext/metrics.go
The motivation for this came from analysing and working on [removing the web vital rating metrics](https://github.com/grafana/xk6-browser/pull/915). It became apparent that we didn't need to expose all these http metrics just yet and instead should focus on the ones that are most used. We used k6 for guidance on this and they have suggested that `browser_http_req_duration` and `browser_http_req_failed` are the most useful. We can add metrics back in when users show interest in them. This will also reduce the overall number of time series metrics.
When you run any of the example test scripts, you should find that we now only display `browser_http_req_duration` and `browser_http_req_failed` `http` based metrics:
```bash
browser_http_req_duration.....: avg=216.97ms min=102.97ms med=208.59ms …
```
=> Remove some of the http metrics

browser/registry.go, browser/registry_test.go
This is needed because we receive the remote's sanitized (quoted) scenario JSON data.
Related: #906 and #888.
=> Add unquoting to the received scenario data

.github/workflows/e2e.yml, .github/workflows/test.yml, Dockerfile, browser/module.go, browser/module_test.go, browser/registry.go, browser/registry_test.go, chromium/browser_type.go, common/browser_options.go, common/browser_options_test.go, env/env.go, examples/device_emulation.js, k6ext/k6test/vu.go, register.go, tests/browser_test.go, tests/browser_type_test.go, tests/frame_manager_test.go, tests/frame_test.go, tests/test_browser.go, tests/test_browser_test.go
This PR refactors the direct usage of `os.LookupEnv` to k6 `LookupEnv`. Please have a look at the commit descriptions for the changes needed.
These new changes provide enhanced testability and consistency throughout the module.
The following are all the environment variables and options that the k6-browser module supports. The outdated `XK6_*` are removed and aligned with the new browser options we have.
```go
// Execution specific.
const (
// InstanceScenarios is an environment variable that can be used to
// define the extra scenarios details to use when running remotely.
InstanceScenarios = "K6_INSTANCE_SCENARIOS"
// WebSocketURLs is an environment variable that can be used to
// define the WS URLs to connect to when running remotely.
WebSocketURLs = "K6_BROWSER_WS_URL"
// …
```
=> Refactor to k6 lookupEnv and abstract env. var. lookup

browser/module.go
We should have removed the exported field after the following change: 710e616957cd2ff4abaae9218ede0d12cbcae267. This PR removes the `Version` field for good.
=> Remove browser module Version

common/browser.go
While exploring the event emitters for another PR I noticed that although we're setting the BaseEventEmitter on browser, we're not actually using it. This is a cleanup and as far as I can tell doesn't affect the behaviour of the app.
=> Remove the BaseEventEmitter from browser

chromium/browser_type.go, common/browser.go, common/browser_test.go, common/frame.go, common/frame_manager.go, common/page.go, common/types.go, tests/launch_options_slowmo_test.go, tests/page_test.go
_TLDR: Skip the initial blank page navigation/lifecycle event if we want to navigate to a non-blank page so that we can wait for the navigation to complete. This way, we can receive custom metrics like Web Vitals. Custom metrics would be randomly skipped without this._
In order to make sure we receive custom metrics like Web Vitals, it is necessary to skip the initial blank page navigation event when navigating to a non-blank page. By doing this, we can wait for the navigation to complete fully. Without skipping this event, custom metrics could be randomly skipped.
<details>
<summary>Before this fix, this test's Web Vital metrics were flaky. Sometimes they show up, and sometimes, they don't.</summary>
```js
import { browser } from 'k6/x/browser';
scenarios: {
ui: …
```
=> Fix race condition in navigation (and lifecycle events)

common/js/web_vital_init.js
Note: We've decided to remove the first commit as the second commit already fixes the issue. Here's the changes from the first commit in case we need it again.
```go
func (p *Page) Close(opts goja.Value) error {
p.logger.Debugf("Page:Close", "sid:%v", p.sessionID())
// forcing the pagehide event to trigger web vitals metrics.
v := p.vu.Runtime().ToValue(`() => window.dispatchEvent(new Event('pagehide'))`)
_ = p.Evaluate(v)
...
}       
```
The [first commit](https://github.com/grafana/xk6-browser/pull/949/commits/5666a13009dfbc90c0e361e3e0a502ea89ffa65b) forces the Web Vital metrics to get triggered on `page.Close`. The page is closing anyway, so there should be no harm in hiding it before it gets closed. Please see [this description](https://github.com/grafana/xk6-browser/pull/943) and …
=> Report Web Vital metrics on every chance

common/frame_manager.go, tests/frame_test.go, tests/static/iframe_home.html, tests/static/iframe_signin.html
In certain navigations, the current frame may have child frames. In these cases, the child frames need to be removed. frameNavigated holds on to a framesMu lock for the whole duration of the frameNavigated.
removeFramesRecursively, which is what removes the child frames, needs the same lock so that it can amend the synchronised variable.
It's also worth noting that this also prevent frameNavigated holding on to a lock when it calls ChildFrames, which requires another lock. It's generally unsafe to hold onto more than one lock at a time.
Closes: https://github.com/grafana/xk6-browser/issues/941
=> Fix deadlock by removing lock in frameNavigated

api/browser.go, browser/mapping.go, common/browser.go, tests/browser_test.go
Now that we can only store a single browserContext per browser, the contexts API doesn't make sense to return more than one browserContext so instead we've refactored it to return the only browserContext or nil.
=> Refactor contexts to context

tests/frame_test.go
This test was flaky due to the state changing during the navigation on `click`. Working with `WaitForNavigation` should resolve this.
=> Add WaitForNavigation with Click in Test

common/js/web_vital_init.js
This reverts commit f25b1d427af756b58a1a424bf66f735b0d710ad5.
In our effort to achieve more consistent Web Vitals reporting, a change was introduced in https://github.com/grafana/xk6-browser/pull/949 to force the Web Vitals library to report metrics [on every value change](https://github.com/GoogleChrome/web-vitals#report-the-value-on-every-change). But, in recent tests we have observed that this was an incorrect configuration, especially for [LCP](https://web.dev/lcp/#when-is-largest-contentful-paint-reported) metric. LCP measures the time it takes to render the largest [image or text block](https://web.dev/lcp/#what-elements-are-considered) visible within the viewport, relative to when the page [first started loading](https://w3c.github.io/hr-time/#timeorigin-attribute). Because there …
=> Revert "Report all web vital metric changes (#949)"

common/page.go, tests/webvital_test.go
After reverting #949 in #964, which main purpose was to improve Web Vitals metrics consistent reporting, we need to provide an implementation that would achieve this consistency without the drawbacks introduced in #949 and explained in #964.
For that purpose this modification to force `pagehide` event has proven to be the better fix so far as commented in https://github.com/grafana/xk6-browser/issues/960#issuecomment-1628654930 and also similar to recommendations given in the Web Vitals library [readme](https://github.com/GoogleChrome/web-vitals):
> Note that some of these metrics will not report until the user has interacted with the page, switched tabs, or the page starts to unload. If you don't see the values logged to the console immediately, try reloading the page (with [preserve …
=> Web Vitals force page hide

common/response.go
While testing the fill form example script against a remote chrome instance, it became apparent that this warning wasn't useful information for the end user. Downgrading from warn to info should avoid noise in the logs.
All other actions which work with `fetchBody` and receive an error will remain to behave as they currently do, which is to assume an error and let the user know -- this still represents the correct behaviour for these actions.
This change will avoid the following errors which seem to occur when the test iteration ends, but dependent responses are still being handled:
```bash
url:https://test.k6.io/static/css/site.css method:GET err:fetching response body: context canceled category=Response:bodySize:fetchBody elapsed=0 ms goroutine=23923 iteration_id=b3d4aaa99ecb1e93 …
```
=> Fix warn level log to debug

browser/registry.go
This PR improves the error message shown when a browser instance for an iteration, which should be automatically initialized as a consequence of the `IterStart` event generated from k6-core, is not found in the browser registry. Because this error might be produced due to the browser type option not being set in scenario definition (the only other possibility is a fault in k6-core/k6 browser implementation), it is better to provide more context information to the user.
=> Improve browser not found in registry error message

common/frame_session.go, log/logger.go
Adds a new `source:browser` log field which allows to distinguish log messages generated by xk6-browser extension from messages generated by k6 core. As mentioned in https://github.com/grafana/xk6-browser/issues/934#issuecomment-1647344562, the `source` label is currently used across k6 codebase.
An example of different log messages after the change applied in this PR including:
- One debug message from k6 browser implementation
- One log [message](https://chromedevtools.github.io/devtools-protocol/tot/Log#event-entryAdded) from browser context execution
- One `console.log` [message](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-consoleAPICalled) from browser context execution
- One `console.log` message from k6 test script execution.
```shell
DEBU[0000] …
```
=> Add browser extension log field

log/logger.go
logs going through loki use the `hooks` logrus concept.
The serialzer was not copying this which meant logs wouldn't have been send to loki.
=> log serializer: fix loki log output

api/frame.go, browser/mapping_test.go, common/frame.go, common/page.go
When we run the k6 browser module against a remote chrome instance, we've found that 1 or more VUs deadlock when running the test in this [issue](https://github.com/grafana/xk6-browser/issues/971). What we have come to realise during the investigation is that the [evaluate](https://github.com/grafana/xk6-browser/blob/a8ebe8cc24f639e0553b1d969df97368db7b5ec5/common/page.go#L430) on the `pagehide` event when `page.close` is called seems to wait indefinitely for a response from chrome, that never seems to arrive.
This is a temporary fix where we use the page's `defaultTimeout` to timeout this `evaluate` request instead of waiting indefinitely. We still need to investigate the root cause of the issue. The downside of this fix is that when this `evaluate` does timeout then we may not receive …
=> Temporary fix for deadlock on pagehide event evaluation when page.close is called

common/connection.go, common/session.go
A detailed description as to why we're doing this can be found [here](https://github.com/grafana/xk6-browser/issues/861#issuecomment-1653312043).
Currently the `msgId`s clash from one session to another as well as with`msgId`s that are sent without a session on the connection event loop.
Generally this isn't an issue, but recently we have found that chrome sometimes returns an error without the `sessionId` that was in the original request msg. When this occurs, we route those error responses to handlers that are waiting on the connection event loop. If there's a clash in `msgId` then the wrong handler will work with the wrong response, which could result in incorrect behaviour. The other issue with routing the response to the wrong handler is that the correct handler could end up waiting …
=> Ensure msgId in CDP requests are unique at the connection scope

browser/registry.go, chromium/browser_type.go
This change ensures that goroutines that were lingering/leaking are cleared once the test ends. This change focuses on the goroutines that were highlighted when trying to create e2e tests for the change in https://github.com/grafana/k6/pull/3235. There could be more goroutines that are lingering/leaking that we need to deal with in the future.
Closes: https://github.com/grafana/xk6-browser/issues/989
=> Fix lingering/leaking goroutines for k6 upgrade

common/browser.go, tests/browser_test.go
While testing for another change, it became apparent that the panic when working with browser.close() would prevent any of the remaining data directories from being cleaned up in the temporary directory. Instead of panicking, we're going to log an error and carry on with rest of the process to try and close the subprocess and eventually delete the data directory. This change does indeed bring about the behaviour we want even when the context has been closed.
=> Fix for data directory not being cleared during browser.close() panic

browser/registry.go
The context in the vu is not thread safe outside of the iteration or the start or end of the vu. By retrieving the vu's context inside the iteration we are working with the vu's context in a thread safe way.
=> Move the vu context creation during iteration

.github/workflows/e2e.yml, .github/workflows/test.yml
The main change (initially) was to work with the `K6_BROWSER_EXECUTABLE_PATH` env var on linux github actions to ensure it picks chrome and not chromium. The github runners have both chromium and google chrome installed. Google chrome is kept up to date whereas chromium isn't. We want to work with the latest version of google chrome (for now, in the future we may want to install the exact version we want to work with).
I also found that the e2e workflow wasn't correctly using the defined matrix, and was only working with `ubuntu-latest`. There are several commits which attempt to resolve this.
Two issues which were discovered but not resolved in the e2e workflow were:
1. the `examples/hosts.js` test script doesn't pass in the Windows stable e2e test. When tested in a Windows 11 computer, …
=> Add K6_BROWSER_EXECUTABLE_PATH in ci

env/env.go, tests/frame_test.go
Defines a `LookupBool` helper.
To make bool lookup queries less verbose in tests.
=> Add a LookupBool utility function

api/browser_context.go, common/browser_context.go, tests/browser_context_test.go
Refactors the browser context cookie API methods and makes them return errors to the mapping layer instead of panicking.
* Better maintainability and provide the base work for #6.
* To increase compliance with the mapping layer, like reducing out-of-band panics and providing controllable testing.
* To improve the error messages for better compatibility with the rest of the module.
Related: #6 and #1005.
=> Refactor the browser context cookie API and error messages

common/frame_session.go, common/page.go
Adds support to retrieve the associated execution context from within all page frames for a given ID.
This is required to associate CDP runtime events for a given page, which include the associated execution context ID (e.g.: see [onConsoleAPICalled](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled)), with the execution context itself among the page frames and their sessions.
Related #1006 .
=> Add `Page.executionContextForID`

common/frame_session.go
Fixes a typo in the `FrameSession.executionContextForID` method for which the frame session's parent was being accessed instead of the calling frame itself.
#1009
=> Fix FrameSession.executionContextForID

api/browser_context.go, browser/mapping.go, common/browser_context.go, examples/cookies.js, examples/fillform.js, tests/browser_context_test.go
Adds `browserContext.cookies()` support.
There will be another PR to add `browserContext.cookies([urls])` support to filter by cookie URLs.
1. To let users access cookies.
2. Providing a better Playwright compatibility.
The docs will be updated when #6 finishes.
Updates #6
=> Add browserContext.cookies()

api/console_message.go, api/page.go, browser/mapping.go, browser/mapping_test.go, common/frame_session.go, common/page.go, examples/pageon.js, go.mod, go.sum, tests/page_test.go
Adds support for `page.on` method. Currently `'console'` event is the only one allowed.
This will allow users to define a function to be executed every time a `console` API is called in the web page context. Such as:
- `console.log`
- `console.debug`
- `console.info`
- `console.error`
- `console.warn`
- `console.dir`
- `console.dirxml`
- `console.table`
- `console.trace`
- `console.clear`
- `console.assert`
- `console.profile`
- `console.profileEnd`
- `console.group`
- `console.groupCollapsed`
- `console.groupEnd`
- `console.count`
See full reference and details at [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/console) for `console` API.
The handler function defined by the user will receive a console message object as input for every call, such as:
```js
ConsoleMessage { …
```
=> Add `page.on`

tests/webvital_test.go
Fixes the flaky test by waiting until the page that it goes to completely loads.
The test sometimes can't receive the WebVital metric emissions. This became evident thanks to #1018.
Failure example:
```go
--- FAIL: TestWebVitalMetricNoInteraction (0.83s)
webvital_test.go:124: 
Error Trace:    /Users/inanc/grafana/k6browser/main/tests/webvital_test.go:124
Error:          Should be true
Test:           TestWebVitalMetricNoInteraction
Messages:       expected browser_web_vital_cls to have been measured and emitted
```
=> Fix WebVitals no interaction test

examples/fillform.js
This change will fix the `check` in the [example/fillform.js](https://github.com/grafana/xk6-browser/blob/main/examples/fillform.js) test.
`check` actually expects a function that returns a `boolean`, as is [documented](https://k6.io/docs/javascript-api/k6/check/). Although the `check` accepts the object as we've been using it, it's not correct. When users work with this example and the type definitions for k6, they will see a red line under the `'header'` in `check`, which will cause confusion and annoyance as to why our own examples have errors.
=> Fix the check on examples/fillform.js

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/team_issues.yaml, .github/PULL_REQUEST_TEMPLATE.md
1. Refines the PR template.
2. Add an issue template for the internal team.
3. Updates the community forum link.
4. Adds the migration guide link to the new issue page.
I can't preview these templates, so IDK how they will look when rendered. **Update:** I found a suboptimal way. Go to the issue template file on the Github UI.
To provide better workflow both for internal and external contributors.
=> Refine PR and Issue templates

common/browser_context.go, examples/cookies.js, tests/browser_context_test.go
1. Fixes the expiration bug while adding cookies.
2. Add an expiring cookie example.
3. Fixes a bug in the test.
Users won't set cookies with an expiration date. Now they can.
Closes #1025
=> Fix the expiration bug while adding cookies

api/browser_context.go, common/browser_context.go, common/browser_context_test.go, examples/cookies.js, tests/browser_context_test.go
1. Adds support for filtering cookies by URLs.
2. Improves tests and examples.
Users can now filter cookies by URLs. See the `example/cookies.js` file for an example.
Updates: #6
=> Filter cookies by URLs

common/page.go, tests/browser_context_test.go, tests/page_test.go
When working with the following APIs, the timeout was being set, but it wasn't then being propagated to the underlying `frameManager` and `frame`s which meant that APIs the relied on the timeout were always working with the default 30 second timeout or the timeout set in the `browserContext`.
```js
page.setDefaultTimeout()
page.setDefaultNavigationTimeout()
```
We want to be able to set the timeouts on the `page` and affect it's APIs, while also having a different timeout on its `browserContext`. This is the behaviour that we want, and at the moment the setting of timeouts through the `page` object does nothing.
Closes: https://github.com/grafana/xk6-browser/issues/940
=> Fix propagation of page timeout

common/frame.go, common/page.go
The following page APIs were not using the correct timeout:
```js
page.reload()
page.setContent()
```
These methods should work with the default navigation instead of the default timeout to match the behaviour in [Playwright](https://playwright.dev/docs/api/class-page#page-set-default-navigation-timeout).
=> Fix reload & setContent to use navigation timeout

common/browser.go
The mutex that is added in this PR is only needed in an edge case where we have multiple instances of k6 connecting to the same chrome instance.
<details>
<summary>Data race stack trace</summary>
```bash
WARNING: DATA RACE
Write at 0x00c001b2ac40 by goroutine 164:
github.com/grafana/xk6-browser/common.(*Browser).NewContext()
/home/runner/work/xk6-browser/xk6-browser/common/browser.go:515 +0xa76
github.com/grafana/xk6-browser/tests.TestMultiConnectToSingleBrowser()
/home/runner/work/xk6-browser/xk6-browser/tests/browser_test.go:334 +0x2fe
testing.tRunner()
/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x216
testing.(*T).Run.func1()
/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:14[93](https://github.com/grafana/xk6-browser/actions/runs/6222592947/job/168868465 …
```
=> Fix read/write race condition for edge case

api/browser_context.go, examples/cookies.js
Adds `js` struct tags to `api.Cookie` to allow Goja to convert `api.Cookie` values.
Goja cannot convert `httpOnly` and `sameSite` fields while sending and retrieving cookies from the JavaScript side.
Updates: #6
=> Cookies: Fix Goja conversions

common/browser_context.go, examples/cookies.js, tests/browser_context_test.go
Fixes the _"unable to clear cookies permissions: invalid context"_ error. This error occurs when `browserContext.clearCookies` is called. See #442 for details.
The `clearCookies` method wasn't using the actual CDP connection.
Closes #442
=> Fix context.clearCookies

examples/multiple-scenario.js
Increasing the max threshold from 1s to 5s for the `browser_web_vital_fcp` metric in the `multiple-scenario.js` example test script.
We're seeing errors in the CI due to the test website being a bit slow since it's continuously being load tested. It feels like it's better to increase the threshold to account for a slow test site due to other load tests being performed against it.
=> Update browser_web_vital_fcp max threshold

api/browser_context.go, browser/mapping.go, common/browser_context.go, common/browser_context_options.go, examples/waitForEvent.js, tests/browser_context_test.go
This refactors, fixes various issues, promisifies the API, and adds tests for the `browserContext.waitForEvent` API.
This initial [motivation](https://github.com/grafana/xk6-browser/pull/1035#pullrequestreview-1630425853) for tackling this was to solely rectify a confusion with the timeout which was sometimes in milliseconds and sometimes in seconds.
While taking a look at the timeout issue, it was clear that there were various issues with this API:
1. It needed a refactor to align with how we parse options elsewhere.
2. The fix on the timeout to work with the default browserContext time.
3. It was unusable unless we promisified it.
4. Parsing of a callable didn't quite work as expected when the options object was passed in.
5. It needed integration and an example test.
There is an …
=> Fix browserContext.waitForEvent

common/js/injected_script.js, tests/page_test.go, tests/static/wait_for.html
Fixes the` _exploreShadowDOM` function defined in the `js/injected_script.js` to check for root's children before recursively exploring them.
This bug was producing sporadic deadlocks in `frame.waitForSelector` method.
Closes #1046 .
=> Fix injected script's Shadow DOM parsing

.github/workflows/block-fixup.yml
Adds a new GH workflow which purpose is to avoid mistakenly introducing fixup commits in the main branch when merging PRs.
Considering our development workflow, introducing fixup commits in the main branch is a mistake that can be made more or less easily, so it's better to have automation set up to prevent it and avoid "polluting" the main branch.
Closes https://github.com/grafana/xk6-browser/issues/1053.
=> Add block fixup commits GH workflow

common/browser_context.go
Refactors `browserContext.clearPermission`.
Brings it inline with how we implement the APIs:
1. Return an error instead of panicking.
Prerequist to https://github.com/grafana/xk6-browser/issues/443
=> Refactor clearPermissions to return an error

browser/mapping.go, browser/mapping_test.go, common/browser.go, tests/browser_test.go
Adds a new `browser.closeContext()` function, which is a handier method to close the current active browser context instead of the more "convoluted" `browser.context().close()`.
Improve UX now that an iteration is limited to a single browser context, therefore extra creation/closing actions might be required.
Updates #1041.
=> Add `browser.closeContext()`

browser/mapping.go, browser/module.go, browser/modulevu.go, browser/registry.go, common/browser_context.go, common/page.go, tests/browser_context_test.go, tests/page_test.go
This PR moves the taskqueue to the mapping layer. The change will affect `page.on` and `browserContext.waitForEvent`.
As we work more with goja and it's runtime, it is starting to find its way into our business logic code. This make maintaining the project more difficult due to having to work with raw `goja.Value` and (more recently) the event loop and `taskqueue`. One of these areas that we do not want in the business logic is most definitely the `taskqueue` which was introduced when we added `page.on`. `page.on` requires a predicate method on the goja runtime since the function is written in JS. Since the goja runtime is not thread safe we need to work with the `taskqueue`. Working with the `taskqueue` in the business logic makes reasoning, maintaining and writing tests very tricky …
=> Move taskqueue to mapping layer

common/browser_context.go, examples/grant_permission.js, tests/browser_context_test.go
This fixes the error when `browserContext.clearPermissions` is called.
It was erroring due to the CDP request not being setup correctly.
Closes: https://github.com/grafana/xk6-browser/issues/443
=> Fix browserContext.clearPermissions

common/browser_context.go, common/event_emitter.go
This remove the browser close event and more importantly the usage of it in `waitForEvent`.
Firstly it is confusing for anyone reading the code that it would seem that `waitForEvent` will unblock when a `close` event occurs. Secondly when a browserContext closes, it doesn't emit a `close` event. Other close actions such as `page.close` do emit a `close` event. We don't want unexpected unblocking when a close action of any type occurs. It feels safer to remove than to fix for now.
Discussion: https://github.com/grafana/xk6-browser/pull/1042#discussion_r1332925743
=> Remove browser close event

common/network_manager.go, common/network_manager_test.go
Refactors `NetworkManager.onLoadingFinished` to fix linter warnings.
This is before fixing bug #1072. Otherwise, We'd have to do the refactoring in #1078.
Related: #1078
=> Refactor NetworkManager.onLoadingFinished

common/network_manager.go, tests/network_manager_test.go
Fixes the request interception deadlock while navigating to another page before loading the current page.
* Please take a look at #1072 for more details.
* Please see #1084 for a prior refactoring work for this PR.
To make complex websites that use many internal iframes and navigations work (like SPAs).
Fixes #1072
=> Fix request interception navigation deadlock

common/network_manager.go, common/network_manager_test.go, tests/network_manager_test.go
Rebases #1072 fixes for `main`. These were reviewed earlier in https://github.com/grafana/xk6-browser/pull/1084 and https://github.com/grafana/xk6-browser/pull/1078. The only difference is this commit that makes some cosmetic changes: 8f9a3858bf5cbf26fad4d6959927b3a8e4f84396.
We should fix the deadlock behavior #1072 also on `main`.
Updated: #1072
=> Merge network interception deadlock bug fix

browser/mapping.go, browser/mapping_test.go, common/frame_session.go, common/network_manager.go, common/page.go, examples/throttle.js, tests/page_test.go, tests/static/ping.html
This adds a new `throttleNetwork` API on `page` which throttles the network from chrome's perspective.
A good use case for throttling the network is to see (within a lab environment) how the frontend reacts when the network is slow, e.g. on a slow 3G connection. With new measurements under a constraint network, users will be able to fine tune their website so that the most important information is returned in an acceptable timeframe.
Updates https://github.com/grafana/xk6-browser/issues/887
=> Add throttleNetwork on page

browser/module.go, browser/module_test.go, common/network_manager.go, common/network_profile.go, examples/throttle.js
Adding predefined network profiles `No Throttling`, `Slow 3G` and `Fast 3G`.
These are the most commonly used during frontend testing when throttling network connections.
These could have been defined in the type definitions repo. To make it simpler for our users to work with these network profiles, it's defined in the browser module repo which will make it available for browser module users.
Updates https://github.com/grafana/xk6-browser/issues/887
=> Add predefined network profiles

browser/mapping.go, common/element_handle.go, tests/element_handle_test.go
This fixes the issue where `Page.Query` (`page.$`) returned an error when no elements match the given selector.
The actual expectation in this scenario, is for the API to return `nil`.
This was tested with the following script:
<details>
<summary>Click me</summary>
```js
import { browser } from 'k6/experimental/browser';
scenarios: {
ui: {
executor: 'shared-iterations',
iterations: 1,
options: {
browser: {
type: 'chromium'
},
},
},
},
}
const page = browser.newPage();
await page.goto("https://test.k6.io");
const result = page.$('input[name="login"]');
if (!result) {
console.log("It's null, hooray!");
}
page.close();
}
```
</details>
Updates: [#982](https://github.com/grafana/xk6-browser/issues/982)
=> Fix error on page.query when no matches with given selector

common/frame.go
The two input arguments `force` and `noWaitAfter` were not being used by `frame.newAction`, and instead were being overriden to always be `false` for both flags.
Some of the APIs that call through to `frame.newAction` (such as `isVisible`) do not need to:
1. wait for a navigation, which is what `noWaitAfter` controls;
2. wait for actionability checks (attached to dom, visible, stable and enabled) and instead should be actioned upon straight away, which is what `force` controls.
=> Use force and noWaitAfter in frame.newAction

browser/mapping.go, common/consts.go, common/element_handle.go, common/frame.go, common/js/injected_script.js, common/page.go
It refactors and updates the query API for `elementHandle` , `frame` and `page` so that we can enable `strict` mode. The change is internal only and doesn't affect the public API.
The change is required so that in the future when we work on an API (such as `locator`) that needs to work with `query` but allow `strict` mode on.
=> Refactor query

common/frame.go, common/page.go, tests/locator_test.go, tests/page_test.go, tests/static/visible.html
This fixes `isVisible` so that it does not wait for an element to match with the given selector, and returns straight away. This makes the `timeout` option obsolete.
There are two reason to make this change:
1. It doesn't make sense to wait for an element to match before checking whether it is visible;
2. It will match Playwrights behaviour which is what some users will expect.
=> Fix isVisible

common/frame.go, common/locator.go, common/page.go, tests/locator_test.go
This refactors `isHidden` for `locator`, `page`, `frame` and `elementHandle`.
Returning an error is a safer way to work instead pf performing a panic which could have unexpected consequences.
Updates: https://github.com/grafana/xk6-browser/issues/688
=> Refactor isHidden to return an error

common/frame.go, tests/locator_test.go, tests/page_test.go
This fixes `isHidden` so that it does not wait for an element to match with the given selector, and returns straight away. This makes the `timeout` option obsolete.
There are two reason to make this change:
1. It doesn't make sense to wait for an element to match before checking whether it is hidden;
2. It will match Playwrights behaviour which is what some users will expect.
=> Fix isHidden

common/element_handle.go, common/frame.go, common/frame_options.go, common/locator.go, tests/locator_test.go, tests/page_test.go
This remove the `timeout` option from `isVisible` and `isHidden` which are part of `elementHandle`, `frame`, `page` and `locator` APIs.
`isVisible` and `isHidden` no longer wait for an element match for the given selector, and so it doesn't make sense to parse and try to work with a timeout parameter.
=> Remove the timeout option from isVisible and isHidden

common/page.go, tests/page_test.go, tests/static/iframe_test_main.html, tests/static/iframe_test_nested1.html, tests/static/iframe_test_nested2.html
`Page.getFrameElement` now finds the root frame. Only the root frame has a `FrameSession`.
With k6 v0.47.0 github.com/grafana/xk6-browser@v1.1.0/common/page.go:274 panicked because the parent session was nil.
Closes: #1087
=> Fix interacting with an element inside nested IFrames

common/frame_manager.go
Fixes a possible NPE in FrameManager.NavigateFrame's event handler to wait for the `navigation` event.
The newDocument field for a navigation event can be nil if the navigation happens within the same document.
Bug.
Closes #1105
=> Fix NPE on NavigateFrame

common/mouse.go, common/mouse_options.go, tests/mouse_test.go, tests/static/dbl_click.html
Fixes the behaviour of the `dblClick` API calls from `locator`, `page`, `elementHandle` and `frame` (they all share the same logic which is implemented in `mouse`).
When a `dblClick` API call is made, it needs to perform two things:
1. Ensure a `onDblClick` event is initiated and any listeners receive the event. This was already part of the implementation.
2. Ensure that double the mouse actions are performed so that an element is clicked on twice, e.g. a counter increments from 0 to 2. This was missing.
Playwright reference: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/input.ts#L199-L219
Updates: https://github.com/grafana/xk6-browser/issues/469
=> Fix dblClick

browser/mapping.go, chromium/browser.go, common/consts.go, common/doc.go, common/element_handle.go, common/frame.go, common/frame_options.go, common/js/doc.go, common/js/injected_script.js, common/locator.go, common/mouse.go, common/mouse_options.go, common/page.go, keyboardlayout/layout.go, log/logger.go, storage/storage.go, tests/doc.go, tests/locator_test.go, tests/mouse_test.go, tests/page_test.go, tests/static/dbl_click.html, tests/static/visible.html
Since the release of [k6 v0.48](https://github.com/grafana/k6/releases/tag/v0.48.0).
Existing PRs wanting to merge `main-next` can target `main` instead.
=> Move main-next to main

README.md
Update selector link in readme.
Previous link was 404ing.
=> Update selector link in readme

common/frame_session.go, common/page.go, common/remote_object.go, log/logger.go, log/logger_test.go, tests/page_test.go, tests/remote_obj_test.go
This change reduces the risk of a panic occurring when the website under test uses `console.log` to print logs.
Currently there is an unknown case where a panic can occur when an object from console.log is unmarshaled and fails with an invalid JSON error. So this isn't fixing the issue but mitigating the risk. This is done by not needing to parse the console.log text at all. The reason behind this choice is that when a user prints something to the console, they don't tend to need the object to be parsed.
Other areas of the module still rely on the existing parse logic which does still attempt to unmarshal the object which is returned when working with APIs such as `JSONValue` and `Eval`.
Updates: https://github.com/grafana/xk6-browser/issues/987
=> Mitigate risk of panic on parse of remote object during console.log

chromium/browser_type.go, chromium/browser_type_test.go
1. Provides a new error message telling users they must install Chromium on their system to run browser tests.
2. Moves `BrowserContext.ExecutablePath` to `ExecutablePath`.
1. The current error message is confusing and just says: _"exec: no command"_.
2. To make `ExecutablePath` testable to prevent future regressions.
Updates #1136
=> Provide a better error message when Chromium isn't found

common/remote_object.go, tests/remote_obj_test.go
This ensures that BigInt remote objects are parsed.
For an unknown reason BigInts are being set as `UnserializableValue` instead of the expected `Value`. This ensures that we correctly deal with the case of BigInt when it is a `UnserializableValue`.
Updates: https://github.com/grafana/xk6-browser/issues/987
=> Fix BigInt remote object parsing

browser/module.go, browser/registry.go, browser/registry_test.go, env/env.go, trace/trace.go
Adds support for traces metadata, which allows users to specify extra _key-value_ fields to be included as attributes for the generated traces.
Allows to define extra attributes that can then be used to query traces from the backend (e.g.: Tempo).
Related: #1100
=> Add support for traces metadata

common/remote_object.go
Adds a new `remoteObjectParseError` error type.
For use when parsing of remote objects fails. It should hopefully help identify what exactly failed to parse.
Updates: https://github.com/grafana/xk6-browser/issues/987
=> Add remoteObjectParseError

browser/registry.go, common/element_handle.go, common/frame_session.go, common/page.go, trace/trace.go
Rename traces attributes.
To better comply with conventions on attribute naming recommended by Open Telemetry. See [docs](https://opentelemetry.io/docs/specs/otel/common/attribute-naming/).
#1100
=> Refactor traces attributes

tests/page_test.go
Refactors the `page.on` integration test.
This change helps us to quickly debug any issues with the `page.on` integration tests by asserting on all individual expectations, which means that in the test output the expectation and actual values will be visible.
=> Refactor page.on integration tests

common/remote_object.go, tests/remote_obj_test.go
This changes the way the output of an array with `console.out` is parsed which affects the display from:
```
{"0":"foo","1":"bar"}
```
to:
```
["foo","bar"]
```
To better represent the array type when it is printed to the console.
Updates: https://github.com/grafana/xk6-browser/issues/987
=> Fix array console output

common/frame_session.go, common/trace.go, tests/tracing_test.go, trace/trace.go
Based on discussions in #1140 , a decision was made to, instead of using the URL as the span name for navigation spans, use the word 'navigation' to identify the action, following the same pattern as the rest of the spans. Due to this, and because a navigation span will always have that fixed span name, it is no longer necessary to accept the span name as input for the method.
Even though the traces generated from k6 browser have some particularities to fit our needs, this change and the changes done in #1140 try to make our implementation more compliant with Open Telemetry conventions and recommendations. These changes will also improve traces searches.
#1100, #1140
=> Refactor TraceNavigation

chromium/browser_type.go
Changes the Chrome/Chromium not installed error messages.
To make the errors clearer (applied as per @heitortsergent's request).
Updates: https://github.com/grafana/xk6-browser/issues/1136
=> Reupdate chrome not installed errs

trace/trace.go
Modifies our tracer implementation to override and wrap the underlying OTEL tracer's `Start()` method so the extra traces metadata set by the `K6_BROWSER_TRACES_METADATA` environment variable are also including when using the OTEL tracer's `Start()` method directly.
Fixes an issue for which the extra metadata set through `K6_BROWSER_TRACES_METADATA` was not included in the iteration root span.
#1104
=> Override OTEL tracer Start() method to include metadata

browser/mapping.go, browser/mapping_test.go, common/locator.go, tests/locator_test.go
This adds a new method `clear` to the `locator` class. This works with the existing `Fill` method which is in the `locator` class. Resources that contributed to the implementation can be found by following the links below:
- https://playwright.dev/docs/api/class-locator
- https://github.com/microsoft/playwright/blob/e30c0a6ff7c48a3abc55eab63fa15d31f6241280/packages/playwright-core/src/client/locator.ts#L130
When typing or filling textboxes or input fields, it's useful to clear existing fields in case they already have values.
Updates: https://github.com/grafana/xk6-browser/issues/1114
=> Add Clear to locator

common/frame.go, common/frame_manager.go, common/network_manager.go
This refactor forces the caller of `NetworkManager.requestFromID` to check the bool value.
This makes it clearer that `requestFromID` could not find a `request` with the given id.
Updates: https://github.com/grafana/xk6-browser/issues/577
=> Refactor NetworkManager.requestFromID

browser/mapping.go, common/locator.go, tests/locator_test.go
Refactor `locator.click` so that it parses the goja value using the goja runtime on the main goja thread and not in a new goroutine.
This will avoid race issues since the goja runtime is not thread safe since it is a JS interpreter that is single threaded.
I've also confirmed that this API doesn't work with goja anywhere else, including when working with `eval`, which is does since it uses `newPointerAction`, which calls `waitForSelector`, that calls ,`evalWithScript` and eventually `eval`, but since `returnByValue` is `false` it doesn't work with goja to transform the return value to a goja value.
Updates: https://github.com/grafana/xk6-browser/issues/1162
=> Refactor locator.click parse

browser/mapping.go, common/element_handle.go, tests/element_handle_test.go, tests/page_test.go
Move the parse logic for `elementHandle.click` into the mapping layer to reduce the call to the goja runtime by one less call.
This will mitigate the risk of a panic occurring due to using the goja runtime in a new goroutine off the main goja thread. This doesn't solve the complete problem and it still relie on using the goja runtime, but that issue can be tracked separately (https://github.com/grafana/xk6-browser/issues/1170).
Updates: https://github.com/grafana/xk6-browser/issues/1169
=> Refactor elementHandle.click parse

browser/mapping.go, common/frame.go, common/page.go, tests/launch_options_slowmo_test.go
This refactors the option parsing out of the promise and into the mapping layer for `frame.click`.
This will help mitigate the risk of a panic occurring due to multiple goroutines accessing the goja runtime (which is not thread safe) concurrently.
More works needs to be done to totally remove the goja runtime usage from within the `frame.click` promise which can be tracked in https://github.com/grafana/xk6-browser/issues/1170.
Updates: https://github.com/grafana/xk6-browser/issues/1172
=> Refactor frame.click option parsing

browser/mapping.go, common/page.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/frame_test.go, tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go, tests/locator_test.go, tests/webvital_test.go
This refactors the option parsing out of the promise and into the mapping layer for `page.click`.
This will help mitigate the risk of a panic occurring due to multiple goroutines accessing the goja runtime (which is not thread safe) concurrently.
More works needs to be done to totally remove the goja runtime usage from within the `page.click` promise which can be tracked in https://github.com/grafana/xk6-browser/issues/1170.
Updates: https://github.com/grafana/xk6-browser/issues/1174
=> Refactor page.click option parsing

browser/mapping.go, common/frame.go, common/page.go, tests/browser_context_options_test.go, tests/browser_context_test.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/frame_test.go, tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go, tests/locator_test.go, tests/mouse_test.go, tests/network_manager_test.go, tests/page_test.go, tests/webvital_test.go
- Moves goja out of option parsing for `frame` and `page` `goto` to mapping.
- Updates tests accordingly.
- Adds two helpers: `Referrer` and `NavigationTimeout` for building options while mapping.
See #1162 for the main reason. Also, the reason for doing both `frame` and `page` `goto` options in the same PR is that the code doesn't compile without the other. Or, it would require a lot of intermediary steps which would be confusing for the commit log.
Updates: #1176
=> Move goja option parsing out of frame and page goto opts

browser/mapping.go, common/frame.go, common/page.go, tests/frame_manager_test.go, tests/frame_test.go, tests/lifecycle_wait_test.go, tests/page_test.go, tests/webvital_test.go
Refactor the parsing of the options of `waitForNavigation` APIs so that they are done outside the promise and therefore on the main goja thread.
This will help mitigate issues which can occur when trying to access the goja runtime from multiple goroutines, which can causes panics since the goja runtime is not thread safe.
Updates: https://github.com/grafana/xk6-browser/issues/1184 & https://github.com/grafana/xk6-browser/issues/1185
=> Refactor parsing of options for waitForNavigation

browser/mapping.go
Refactor the parsing of the options for the `browserContext.waitForEvent` API so that it is done outside the promise and therefore on the main goja thread.
This will help mitigate issues which can occur when trying to access the goja runtime from multiple goroutines, which can causes panics since the goja runtime is not thread safe.
Updates: https://github.com/grafana/xk6-browser/issues/1187
=> Refactor parsing of options for waitForEvent

browser/mapping.go, common/frame.go, common/page.go, k6ext/k6test/vu.go, tests/page_test.go, tests/tracing_test.go
Refactor the parsing of the arguments of `waitForFunction` APIs so that they are done outside the promise and therefore on the main goja thread.
This will help mitigate issues which can occur when trying to access the goja runtime from multiple goroutines, which can causes panics since the goja runtime is not thread safe.
Updates: https://github.com/grafana/xk6-browser/issues/1180 & https://github.com/grafana/xk6-browser/issues/1181
=> Refactor parsing of arguments for waitForFunction

common/execution_context.go, common/helpers.go, tests/launch_options_slowmo_test.go, tests/locator_test.go
- Adds assertions for goja value escapes to `ExecutionContext`.
- Marks the failing tests as skipped until we fix them all.
Note that this will be added to the `fix/goja-execctx-eval` branch. Then, we'll fix the failing tests in other PRs (See #1182). So it's safe to approve this.
- To ensure that no Goja value escapes to `ExecutionContext`.
Updates: #1182
=> Add goja escape assertions

browser/mapping.go, common/element_handle.go, common/execution_context.go, common/frame.go, common/helpers.go, common/helpers_test.go, common/js_handle.go, common/locator.go, common/page.go, common/remote_object.go, common/remote_object_test.go, common/screenshotter.go, examples/colorscheme.js, tests/browser_context_test.go, tests/element_handle_test.go, tests/js_handle_get_properties_test.go, tests/launch_options_slowmo_test.go, tests/locator_test.go, tests/mouse_test.go, tests/page_test.go, tests/remote_obj_test.go, tests/test_browser.go
All of these changes are forced by the compiler and tests while working on `ExecutionContext.Eval`.
- We can now use CDP/JS values without involving Goja.
- Removes Goja from `ExecutionContext`. After this refactoring, everything started to fall apart, and we needed to refactor many parts of the code together. I couldn't split the second commit into smaller commits because it would break the build.
- Removes Goja handling from most of the `common` types.
- After this change, Goja can no longer do the conversion. So we add a generic `convert` helper to convert `any` values to type-safe values. There is another one in the test browser as a helper for the tests.
These additional PRs are created that will merge into this one.
- https://github.com/grafana/xk6-browser/pull/1191
- …
=> Remove Goja from Execution Context Eval and from related parts

browser/mapping.go, common/element_handle.go, common/frame.go, common/locator.go, common/page.go, tests/launch_options_slowmo_test.go, tests/locator_test.go
All `DispatchEvent` methods now:
- Return errors.
- Moves their option parsing to the mapping layer.
- Prevent passing down Goja values.
Fixes tests:
- TestLocator
- TestBrowserOptionsSlowMo
- The goja escape was related to `DispatchEvent`s.
- This is a necessary fix to remove passing Goja values to `ExecutionContext`.
- See https://github.com/grafana/xk6-browser/pull/1191.
- See also #1182.
Updates: #1182
=> Fix goja escape from DispatchEvents

common/frame_session.go, common/page.go, common/remote_object.go
Returning an error from `parseConsoleRemoteObject` instead of logging an error.
There is another use case for `parseConsoleRemoteObject`, which is when `JSONValue` is called. At the moment this API uses `valueFromRemoteObject` which returns a `goja.Value`.
Interestingly, the return value from `JSONValue` is always converted to string before being returned to the caller, so the extra step to convert to goja and then back to string is not needed.
Updates: https://github.com/grafana/xk6-browser/issues/1168
=> Refactor parseConsoleRemoteObject to return error

common/frame.go, common/frame_session.go, common/js_handle.go, tests/js_handle_get_properties_test.go, tests/page_test.go
Refactor `JSONValue` to use `parseConsoleRemoteObject`.
This will help avoid working with the goja runtime outside of the mapping layer and therefore avoid possible race conditions with the unsafe goja runtime. `JSONValue` wasn't ever working with the goja values and so it made sense to always work with string values.
Updates: https://github.com/grafana/xk6-browser/issues/1168
=> Refactor JSONValue to use parseConsoleRemoteObject

tests/tracing_test.go
The close wasn't being called on testServer which is a requirement when using it.
To avoid leaks or unknown consequences.
=> Fix testServer close operation

browser/mapping.go, browser/module.go, browser/modulevu.go, common/element_handle.go, common/page.go, common/screenshotter.go, storage/file_persister.go, storage/file_persister_test.go, tests/element_handle_test.go, tests/page_test.go
This change adds a new `LocalPersister` which will replace how the `screenshotter` writes to the local disk.
This is the first step in removing the details of how and where the screenshot is being saved, allowing us to work with either a `LocalPersister` or (yet to be implemented) `RemotePersister`.
Updates: https://github.com/grafana/xk6-browser/issues/1155, https://github.com/grafana/xk6-browser/issues/1156 and https://github.com/grafana/xk6-browser/issues/1157.
=> Add a localPersister

browser/mapping.go, common/element_handle.go, common/page.go, common/screenshotter.go, tests/element_handle_test.go, tests/page_test.go
This refactors the parsing of the goja options for `frame.screenshot` and `page.screenshot` to the mapping layer, as well as moving goja out of screenshotter. This means that the screenshot business logic is free of goja.
It also changes the `screenshotter` to return a `[]byte` instead of a pointer to it (`*[]byte`).
The options should be parsed out of the `goja.Value` representation in the mapping layer to avoid goja escaping into the business logic which makes the business logic more complex and this will also help if we convert this method into async.
There's no reason to return a `*[]byte` as far as i can tell.
Updates: https://github.com/grafana/xk6-browser/issues/1064
=> Refactor goja out of screenshots and byte pointer changes

storage/file_persister.go, storage/file_persister_test.go
This adds a remote persister, which will upload files (screenshots) to the remote location. It uses a two request mechanism to:
1. Retrieve a presigned url for the given file with the name.
2. Uploads the file with the retrieved presigned url.
Although it is possible to batch retrieve the pre-signed url, there is no easy way to retrieve the filenames that are required to retrieve the presigned urls, so it needs to be done one at a time when a request to persist the screenshot comes in.
To enable the browser module to upload screenshots to a remote location.
Updates: https://github.com/grafana/xk6-browser/issues/1159
=> Add RemoteFilePersister

browser/helpers.go, browser/mapping.go, examples/dispatch.js, examples/evaluate.js
- Fixes #1204 
- Adds two examples to test the behavior
- To prevent panics while passing `null` values to methods.
Updates: #1204
=> Fix 1204: panic while exporting nil goja values

.github/workflows/block-fixup.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Updates Github actions.
- There are new and stable action versions.
- k6-core has upgraded its runners as well, and we want to be compatible.
- Newer actions require Go 1.20+.
N/A
=> Bump Github action versions

.github/workflows/block-fixup.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/test.yml
We should ensure our test pipelines also work with the same version of go as k6.
k6 is using go APIs which are in v1.20
=> Update go version in CI test pipeline

examples/shadowdom.js
Adds a shadow DOM E2E example test script.
To verify the behavior and redirect users to the example.
Updates: https://github.com/grafana/xk6-browser/issues/1210
=> Add a shadow DOM example

.github/workflows/lint.yml, .github/workflows/test.yml, .golangci.yml
Fixes and bumps the Go versions for the linter and test Github actions.
- The current linter Go version 1.19 won't work for the linter action after #850 change. See the error [here](https://github.com/grafana/xk6-browser/actions/runs/7897531005/job/21553265573?pr=850).
- Test runners are upgraded to Go 1.21 as per k6-core.
#850, #1214, #1212
=> Bump linter and test Github action Go versions

common/remote_object.go, common/remote_object_test.go
This should be merged after upgrading Go's previous version on CI (currently 1.19) to 1.20. Currently, the tests fail because of that.
Updates #738.
=> Remove multierror and refactor to Go errors.Join

common/element_handle.go
- Degojafies `offsetPosition`.
- `Frame` and `ElementHandle` no longer depend on Goja while doing `newPointerAction`s.
Stability.
Updates: #1170
=> Remove goja from newPointerAction

common/frame.go
Adding `nil` checks in `requestByID`.
For unknown reasons `mainFrameSession` or `mainFrameSession.networkManager` (it's unknown exactly which one) are `nil`, which has caused NPDs. We're adding `nil` checks here to prevent the NPDs, but we're now logging to see what components are `nil` to try and work out what is causing the NPD.
Updates: https://github.com/grafana/xk6-browser/issues/986
=> Add nil checks in requestByID

common/browser.go, common/browser_context.go, common/connection.go, common/connection_test.go, common/session_test.go, tests/browser_test.go
With this fix, the browser module can now work with an **unlimited** number of VUs and iterations (_limited by the machine power and the browser, of course_). As explained in #1112, this PR separates browser contexts to make each iteration focus solely on its pages rather than those created by other iterations. This brings:
- Efficiency (at least 10X depending on the number of VUs)
- Better debugging (less log noise)
- Possibly fewer deadlocks (none seen so far in our tests)
Tested with the script in #971 and saw no deadlocks.
Note: This PR aims to apply this fix with minimum code changes to avoid disrupting the module's working.
Please take a look at #1112 and #971 for more details.
We're adding a separate `onAttachedToTarget` hook to act precisely even before the module's event system …
=> Fix Multi VU deadlock by isolating browser contexts

browser/mapping.go, common/browser_context.go
Refactor browserContext.addinitscript to move the goja code into the mapping layer.
This will help isolate goja specific code in the mapping layer.
https://github.com/grafana/xk6-browser/issues/1064
https://github.com/grafana/k6-cloud/issues/2066
=> Refactor goja out of browserContext.addinitscript

browser/module.go, browser/modulevu.go, env/env.go
This adds the test run ID to the `RootModule` allowing any browser component to work with the test run ID.
This is a requirement to allow better integration with external tools (such as faro)to be used to label sessions with a test run ID. The test run id will eventually be populated in the `window.k6` object which is injected into each and every `browserContext` and `page`.
The change localises the retrieval of the test run id in one place instead of having every component need to do a lookup for an env var.
Updates: https://github.com/grafana/k6-cloud/issues/2066
=> Add test run id to RootModule

common/execution_context.go, tests/page_test.go
This fixes the error that is returned when a user works with the `evaluate` APIs when a navigation isn't occurring:
```js
const page = browser.newPage();
const blah = page.evaluate("1+1");
console.log(blah);
page.close();
```
This used to return `GoError: evaluating JS: execution context changed; most likely because of a navigation`, but now it returns `given expression does not evaluate to a function`.
The new error better represents what the user can do to fix the problem instead of being left confused when no navigation has occurred. In the example above and with the new error, they should be able to work out that `evaluate` only works with callable functions.
https://github.com/grafana/k6-cloud/issues/2066
=> Fix error for `evaluate` APIs

common/element_handle.go, common/element_handle_options.go, common/frame.go, common/frame_options.go, common/js/injected_script.js, common/page.go, tests/setinputfiles_test.go
Add `setInputFiles` support.
Here is a test script you can test this functionality with
**index.html:** (served by e.g. ```python3 -m http.server 3080```)
```
<html>
<head>
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
</head>
<body>
<form method="POST" action="/upload" enctype="multipart/form-data">
<input type="file" name="upl" id="simple-upload" multiple />
<input type="submit" value="Send" />
</form>
<div id="dropzone"/>
<script>
let myDropzone = new Dropzone("div#dropzone", { url: "/upload", autoProcessQueue:false });
</script>
</body>
</html>
```
**test.js:**
```
import { browser } from 'k6/experimental/browser';
import { check } from 'k6';
scenarios: {
ui: {
executor: 'shared-iterations',
vus: 1,
iterations: 1,
options: { …
```
=> Add setInputFiles to ElementHandle

common/element_handle.go, tests/locator_test.go, tests/static/locators.html
Fixes a bug, where calling fill() on textarea throws error. #1225 
fill() should work for any contenteditable node. Currently it works only for ```<input>```
#1225
=> Fix fill functionality for textarea

common/element_handle.go, common/js/injected_script.js, tests/page_test.go, tests/static/shadow_and_doc_frag.html
This adds javascript code to convert a `DocumentFragment` into a `Document`.
`DocumentFragment`s do not implement `evaluate` and so do not work with `XPath` selectors. When a `DocumentFragment` is encountered it will convert that to a `Document` so that `evalaute` with `XPath` selectors can be performed.
Updates: https://github.com/grafana/xk6-browser/issues/1243
=> Fix DocumentFragment XPath evaluate

common/element_handle.go, common/element_handle_options.go, tests/setinputfiles_test.go
Removing the support for `setInputFiles` to read off of the filesystem with the os package.
We do not want k6 to be able to read anything off of a filesystem that it shouldn't be reading. Instead anyone wishing to work with files on the filesystem should look to use the built in [experimental fs module](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/fs/). The fs module abstracts away the detail of how it loads the required file for when working in a remote environment. It also reduces the risk of OOMs. A simple example can be found below:
<details>
<summary>Example working with `setInputFiles` and the fs module</summary>
```js
import { browser } from 'k6/experimental/browser';
import encoding from 'k6/encoding';
import { open } from 'k6/experimental/fs';
export const …
```
=> Remove the setInputFiles os.read support

common/frame_manager.go
Remove logging in-flight requests when a request is failed.
We noticed we shouldn't find an internally failed request, as it can cause race condition issues within the module's internal components. Also, we've decided that logging in-flight requests only adds noise without bringing any tangential value.
We keep logging the failed request, though.
Updated #986
=> Remove logging in-flight requests

browser/mapping.go, browser/mapping_test.go, common/element_handle.go, common/frame.go, common/locator.go, common/page.go, common/touchscreen.go, tests/locator_test.go
Degojaifies the `Tap` methods.
See: #1064 and #1251.
Updates #1251 and #1064.
=> Degojaify the `Tap` methods and remove `panic`s

examples/touchscreen.js
Fixes the race condition in the example.
The touchscreen example was printing out the warning (before the fix):
```
WARN[0002] failed to hide page: evaluating JS: Cannot find context with specified id  category="Page:Close" elapsed="0 ms" source=browser
```
The reason is "tapping" causes a page navigation, and we try to close the page while the navigation is in progress.
=> Fix the touchscreen example

tests/tracing_test.go
Catch the web vital spans after the `page.close` API call is made. This should definitely cause the web vitals to emit and be received in time before the sub-test completes.
Instead of a sleep to wait for a web vital, which is problematic on slower machines that can cause the sub test to fail, catch the web vital spans that are emitted/received when the page.close() API is called.
I've ran the integration tests 10 times and there were no failures with the tracing tests, whereas usually I would get 2-3 failures.
https://github.com/grafana/xk6-browser/issues/1150
=> Fix web vital trace test

browser/mapping.go, common/browser.go, common/locator.go, common/page.go, tests/locator_test.go
Refactor the APIs that are currently traced so that they return an error instead of panicking.
This refactor is to enable to the work for https://github.com/grafana/xk6-browser/issues/1249. We need access to the error itself so that it can be added to the span.
https://github.com/grafana/xk6-browser/issues/1249
=> Refactor APIs that are traced

browser/mapping.go, browser/mapping_test.go, chromium/browser_type.go, common/browser_context.go, common/frame.go, common/http.go, common/js_handle.go, common/page.go, common/worker.go, tests/browser_test.go
Removing the unimplemented API function bodies.
It's confusing when auditing APIs to have some that do not have any implementation. It's as if they are a priority, which is not the case. We will add the APIs that we think we need and when the community asks for them.
=> Remove unimplemented apis

browser/mapping.go, browser/mapping_test.go, examples/touchscreen.js
Makes `Tap` async.
**Note:** We'll merge this once we conclude on an approach to rollout the Async API.
See #1251.
#1251
=> Make `Tap` async

common/js_handle.go
Ignore context canceled errors when attempting to dispose of a `frame`.
When testing websites which contain `iframe`s, they can cause a `panic: GoError: dispose: canceled` panic. This is confusing behaviour since after investigating the issue it turns out that the dispose doesn't need to occur since the `page` the `iframe` is associated to is already closed. More details can be found in this [comment](https://github.com/grafana/xk6-browser/issues/1089#issuecomment-2040220958).
It's worth noting that this is more of a work around. A better solution might be to not end the iteration until all the CDP messages between k6 and Chrome ended successfully, but this would require quite a bit of refactoring and possibly more control over the iteration. …
=> Fix dispose context canceled errors

common/browser.go, common/browser_context.go, common/element_handle.go, common/locator.go, common/page.go, common/trace.go
Adding errors to the API spans that currently exist.
When a user views the traces for the test, it's useful to see whether an error occurred and in which API call. This will help highlight spans where errors occurred and therefore caused the test iteration to fail.
https://github.com/grafana/xk6-browser/issues/1249
=> Add errors to spans

common/execution_context.go
Replace `Warn` with `Warnf`.
We used `Warn` incorrectly.
=> Fix log warn in execution context

common/frame.go, common/frame_session.go
This fixes a problem with setting the execution context when testing a website that uses iframes. Without this fix it could end up in an infinite loop when `waitForExecutionContext` is called.
There is a race condition when it comes to attaching iframes and the execution context that apply to these frames. What usually occurs is:
1. An exec context for about:blank is first set;
2. A new set event is received for exec context for the url pointing to the actual destination for the iframe;
3. Finally the execution context for about:blank is destroyed, not for the second execution context.
This is the order of events when iframes are in use on a site, and so it is safe to nil the original execution context and overwrite it with the second one.
The exec context destroyed event will not remove …
=> Fix execution context setting for iframes

browser/browser_mapping.go, tests/browser_context_test.go
This fixes an issue when working with a second tab (i.e. opening a new page in the same existing browserContext), and navigating to a url.
You can also test with the following test script to see what happens without the fix and with the fix:
```js
import { browser } from "k6/x/browser";
scenarios: {
ui: {
executor: "shared-iterations",
options: {
browser: {
type: "chromium",
},
},
},
}
};
const page = browser.newPage();
await page.goto("https://k6.io", { waitUntil: "networkidle" });
const context = browser.context();
const page2 = context.newPage();
await page2.goto("https://k6.io", { waitUntil: "networkidle" });
page.close();
}
```
This issue would arise as soon as any API is used from the new page instance. This was occurring …
=> Fix NPD when using goto on a second page

browser/browser_mapping.go, examples/colorscheme.js, examples/device_emulation.js, examples/dispatch.js, examples/elementstate.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/locator.js, examples/locator_pom.js, examples/querying.js, examples/screenshot.js, examples/throttle.js, examples/waitForEvent.js, examples/waitforfunction.js, tests/browser_context_test.go
=> Async `browser.newContext`

browser/browser_mapping.go, tests/browser_context_test.go
=> Async `browser.closeContext`

browser/browser_mapping.go, examples/cookies.js, examples/keyboard.js, examples/mouse.js, examples/multiple-scenario.js, examples/pageon.js, examples/shadowdom.js, examples/touchscreen.js, tests/browser_context_test.go, tests/browser_test.go, tests/browser_type_test.go, tests/page_test.go, tests/tracing_test.go
=> Async `browser.newPage`

browser/keyboard_mapping.go, browser/mapping_test.go, browser/page_mapping.go, common/element_handle.go, common/keyboard.go, common/keyboard_test.go, tests/keyboard_test.go
Maps the forgotten `Keyboard`, adds a test, and turns panics into errors.
To make the async migration.
#1304
=> Prepare `Keyboard` for Async migration

browser/keyboard_mapping.go, examples/keyboard.js
=> Async `Keyboard`

k6ext/k6test/vu.go, tests/browser_context_test.go, tests/browser_test.go, tests/browser_type_test.go, tests/helpers.go, tests/page_test.go
Adds test helpers for async VU execution.
* Reduce redundancy and mistakes.
* Improve readability and productivity.
=> Add test helpers for async VU execution

browser/browser_context_mapping.go, browser/page_mapping.go
Fixes forgotten `page` and `context` mappings.
Otherwise, the module's behavior will be unpredictable and wrong.
=> Fix `page` and `context` mappings

browser/browser_context_mapping.go, browser/mapping_test.go, browser/page_mapping.go, common/browser.go, common/browser_context.go, common/frame_session.go, common/network_manager.go, common/page.go, tests/browser_context_options_test.go, tests/browser_test.go
Turns panics into errors.
#1295
=> Prepare `BrowserContext` for async migration

browser/browser_context_mapping.go, examples/colorscheme.js, examples/cookies.js, examples/device_emulation.js, examples/dispatch.js, examples/elementstate.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/locator.js, examples/locator_pom.js, examples/querying.js, examples/screenshot.js, examples/throttle.js, examples/waitForEvent.js, examples/waitforfunction.js, tests/browser_context_test.go
=> Async `BrowserContext`

common/frame_session.go, tests/page_test.go
Move the CDP request `RunIfWaitingForDebugger` to be called first when creating a `FrameSession`.
We have identified that the call to `RunIfWaitingForDebugger` wasn't being performed at the correct time when a new page was created after a link was clicked on that opened the page.
This is currently the simplest and safest solution. I tried to place some of the CDP actions that are in `NewFrameSession` within their own goroutines but there were data races.
Updates: https://github.com/grafana/xk6-browser/issues/827
=> Fix navigate to link in new page

browser/mapping_test.go, common/locator.go, tests/locator_test.go
Turns panics into errors.
#1305
=> Prepare `Locator` for async migration

browser/locator_mapping.go, examples/dispatch.js, examples/fillform.js, examples/locator.js, examples/locator_pom.js, examples/shadowdom.js, tests/page_test.go
=> Async `Locator`

browser/mapping_test.go, common/element_handle.go, common/frame.go, tests/element_handle_test.go, tests/keyboard_test.go, tests/mouse_test.go, tests/page_test.go
Turns panics into errors and reorders the methods for consistency.
#1296
=> Prepare `ElementHandle` for async migration

browser/element_handle_mapping.go, examples/elementstate.js, examples/getattribute.js, examples/mouse.js, examples/querying.js, examples/touchscreen.js
=> Async `ElementHandle`

common/frame_manager.go, common/frame_session.go
This fixes an issue where a page with an iframe panics during a navigation.
The reason are two fold:
1. Firstly we didn't have a reference to the iframes child frame. This was resolved by adding handling the frame tree of the iframe. It's not a mainframe but it still needs to be handled correctly so that we have a reference to the iframe and its children.
2. Now that we have the child frame, we don't want it to be removed during a detach (of type swap). We protect against this by checking the session of the incoming detach event and the frame that it is trying to detach. If they don't match we ignore the request.
Updates: https://github.com/grafana/xk6-browser/issues/1341
=> Fix iframe panic on navigation

browser/request_mapping.go, common/http.go
Return `nil` when the value is empty for `postData` and `postDataBuffer`.
This follows JS conventions.
https://github.com/grafana/xk6-browser/issues/1308
=> Refactor request to act more like JS

browser/request_mapping.go
Remove unused name field from request mapping.
Linter error.
https://github.com/grafana/xk6-browser/issues/1308
=> Remove unused name field from request mapping

browser/mapping_test.go, common/frame.go, common/page.go, tests/element_handle_test.go, tests/frame_test.go, tests/keyboard_test.go, tests/launch_options_slowmo_test.go, tests/locator_test.go, tests/page_test.go
Turns panics into errors only for `Page`'s first set of methods. The rest will be in another PR.
#1307
=> Prepare `Page` for async migration part #2

browser/mapping_test.go, browser/page_mapping.go, common/frame.go, common/frame_session.go, common/network_manager.go, common/page.go, tests/element_handle_test.go, tests/frame_test.go, tests/keyboard_test.go, tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go, tests/locator_test.go, tests/mouse_test.go, tests/page_test.go, tests/setinputfiles_test.go
Turns panics into errors only for `Page`'s final set of methods.
#1307
=> Prepare `Page` for async migration part #3

browser/page_mapping.go, examples/colorscheme.js, examples/cookies.js, examples/device_emulation.js, examples/dispatch.js, examples/elementstate.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/keyboard.js, examples/locator.js, examples/locator_pom.js, examples/multiple-scenario.js, examples/pageon.js, examples/querying.js, examples/screenshot.js, examples/shadowdom.js, examples/throttle.js, examples/touchscreen.js, examples/waitForEvent.js, examples/waitforfunction.js, tests/browser_context_test.go, tests/browser_test.go, tests/browser_type_test.go, tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go, tests/page_test.go
=> Async `Page`

browser/request_mapping.go
Revert `request.headers` and `request.size` to sync.
Both these APIs are safe to stay as sync because:
1. In Playwright they are sync APIs.
2. They don't make any long running IO calls or long running processes.
=> Revert request.headers and request.size to sync

browser/browser_mapping.go, browser/mapping_test.go, common/browser.go, tests/browser_test.go
* Precalculates the browser version information after connecting to the browser.
* Removes `error` from the `Version` and `UserAgent` methods as the version information is cached.
* Downside: The browser version information is always fetched to cache it.
#1359
=> Precalculate `browser.version` and `browser.userAgent` to prevent the I/O call

examples/elementstate.js, examples/mouse.js, examples/querying.js, examples/touchscreen.js
Fixes `await` usage.
The examples were incorrectly using `await`, leading to [incorrect results](https://github.com/grafana/xk6-browser/actions/runs/9364831439).
=> Fix Async examples

browser/mapping_test.go, browser/response_mapping.go, common/http.go, tests/browser_context_options_test.go, tests/page_test.go
* Turns panics into errors for `Response`.
* Turns `Response` mapping into async.
#1309
=> Async `Response`

browser/js_handle_mapping.go, common/element_handle.go, common/element_handle_test.go, common/frame.go, common/frame_manager.go, common/frame_session.go, common/js_handle.go, common/page.go, common/screenshotter.go, tests/element_handle_test.go
Prepare `JSHandle` to be async by turning panics into errors.
* Stability.
* To convert `JSHandle` to async.
#1303
=> Async `JSHandle` prepare

browser/js_handle_mapping.go, examples/pageon.js
=> Async `JSHandle`

common/remote_object.go, common/remote_object_test.go, tests/remote_obj_test.go
Improve `valueFromRemoteObject` `null` detection by returning a Go `nil` instead of `"null"` as a string.
Previously, we couldn't detect a null value:
```go
v, _ := page.GetAttribute("#el", "missing", nil)
assert.Nil(t, nil, v) // v is not nil. it's "null"
```
After this PR, `v` will be `nil` instead of `"null"` as a string. This enables us to detect `nil` in methods like `GetAttribute`, `TextNode`, etc., to tell the user that what they're looking for does not exist instead of returning `"null"` or an empty string.
=> Improve `valueFromRemoteObject` `null` detection

browser/frame_mapping.go, common/frame.go, common/remote_object.go, common/remote_object_test.go, tests/remote_obj_test.go
* There are a lot of commits. Luckily, each commit is small and corresponds to a method.
* The PR removes panics from a few methods and turns them into async. I don't want to split the PR because of a few panicking methods. But I used different commits for revertability.
#1302
=> Async `Frame`

browser/element_handle_mapping.go, browser/frame_mapping.go, browser/locator_mapping.go, browser/mapping_test.go, browser/page_mapping.go, common/element_handle.go, common/frame.go, common/locator.go, common/page.go, tests/element_handle_test.go, tests/frame_test.go, tests/locator_test.go, tests/page_test.go
The `GetAttribute` methods now return `false` when the attribute is missing.
Previously, these methods returned an empty string (`""`). That approach makes it impossible to distinguish between whether the attribute is missing or empty.
I'm happy to convert the tests into table tests if desired.
#428
=> Improve `GetAttribute` `null` attribute detection

browser/element_handle_mapping.go, browser/frame_mapping.go, browser/locator_mapping.go, browser/mapping_test.go, browser/page_mapping.go, common/element_handle.go, common/frame.go, common/locator.go, common/page.go, tests/element_handle_test.go, tests/frame_test.go, tests/lifecycle_wait_test.go, tests/locator_test.go, tests/mouse_test.go, tests/page_test.go
The `TextContent` methods now return `false` when the element's text content cannot be grabbed (like a JS `document`). I've added tests only for `ElementHandle` as the other types have their `TextContent` tests.
Previously, these methods returned an empty string (`""`). That approach makes it impossible to distinguish between whether the text content is missing or empty.
#428
=> Improve `TextContent` `null` element detection

common/page.go
Fixes an NPE when the new document or request is missing.
To fix this error.
```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14bee2c]
goroutine 111 [running]:
github.com/dop251/goja.(*Runtime).runWrapped.func1()
github.com/dop251/goja@v0.0.0-20240516125602-ccbae20bcec2/runtime.go:2442 +0xe5
panic({0x18327c0?, 0x2db2e80?})
runtime/panic.go:770 +0x132 …
```
=> Fix empty `newDocument` on `page.reload`

browser/browser_mapping.go, browser/mapping_test.go, browser/sync_browser_mapping.go, common/browser.go, common/browser_context.go, tests/browser_context_options_test.go, tests/element_handle_test.go, tests/network_manager_test.go, tests/test_browser.go
- Moves `BrowserContextOptions` out of the business logic.
- Sets default options in `NewBrowserContext` to prevent nil pointer issues in the rest of the module. _Later, we can turn some of these pointer fields into value types to take advantage of their zero values._
- Updates tests to work with the new structure.
These changes should had to be made in the single commit to be atomic.
See #1269.
=> Desobekify `Browser`

common/helpers.go
Try to prevent blocking on channel send.
It is possible (and noticed in the real world) that the goroutine might enter the out select and then by the time get to writing to the channel back for the event handling to have been canceled.
=> Fix potential races in createWaitForEvent*

browser/element_handle_mapping.go, browser/frame_mapping.go, browser/locator_mapping.go, browser/mapping_test.go, browser/page_mapping.go, common/frame.go, common/locator.go, common/page.go, examples/elementstate.js, tests/element_handle_test.go, tests/frame_test.go, tests/locator_test.go, tests/page_test.go
See #1340.
See #1340.
Updates #1340
Closes #354 
Closes #368
=> Add `setChecked`

common/frame_session.go, common/page.go
This PR fixes an issue where the browser module would panic when navigating to certain website with iframes on them. The error is `panic: GoError: attaching iframe: attaching iframe target ID 153A0D279584840F49FB1E718A8297AB to session ID DA84F3DFA9B0CA220314557F25BC8B37: getting browser window ID: No web contents for the given target id (-32000)
`
The reason for this is when the browser comes to attach an iframe, some iframes do not have any UI elements, which sets a state within [chromium such that no windowID can be returned](https://chromium.googlesource.com/chromium/src/+/665cdea2f5f29e166ad455b5021154456944fcbc/headless/lib/browser/headless_devtools_manager_delegate.cc#633) when one is requested for. This causes a panic [here](https://github.com/grafana/xk6-browser/blob/main/common/f …
=> Fix panic on iframe attach

browser/sync_page_mapping.go
Returns early from `page.reload` (async API only).
Avoids unnecessary panics and aborts since it is expected that response can be nil.
Updates: https://github.com/grafana/xk6-browser/issues/1407
Linked to: https://github.com/grafana/xk6-browser/pull/1387
=> Fix panic on nil response during page.reload

browser/page_mapping.go
Avoid the null exception when reload is called a response is null.
Avoids an error that isn't an error. Response can be null.
Linked to: https://github.com/grafana/xk6-browser/pull/1408
Updates: https://github.com/grafana/xk6-browser/issues/1407
=> Fix async reload when it returns a null response

storage/file_persister.go, storage/file_persister_test.go
Improve file persister naming.
- Move checkStatus utility to the bottom to reduce noise while reading
- pre-signed to presigned and preSigned to presigned for consistency
- getPresignedURL to requestPresignedURL for saying it's a request
- newUploadRequest to newFileUploadRequest for specificity
- readResponseBody generic naming to specific readPresignedURLResponse
- preSignedURLGetterURL to presignedURLRequestURL for consistency
For consistency and readability (hopefully).
Updates grafana/k6-cloud#2539
=> Tiny refactoring for file uploading code

common/frame_manager.go, common/frame_session.go, tests/tracing_test.go
This fixes the navigation span so that the duration is longer than the duration of the child spans. This fix is to start the navigation span earlier in `onFrameStartedLoading`. It also required us to differ adding the url attribute to the navigation span to when it was ended since we don't have knowledge of the new url in `onFrameStartedLoading`.
This ensures that the child span values make sense with respect to the parent/navigation span they are part of.
Before the fix:
After the fix:
Updates: https://github.com/grafana/xk6-browser/issues/1413
=> Fix navigation span start

common/page.go
Checking for `nil` after calling `dom.DescribeNode()`.
The node from `dom.DescribeNode()` can be `nil`, so checking for `nil` before proceeding.
Updates: https://github.com/grafana/xk6-browser/issues/1416
=> Fix NPD in getOwnerFrame

common/element_handle.go
Ensuring that the goroutine can exit early if the context is closed.
There's a chance that the goroutine [reading](https://github.com/grafana/xk6-browser/blob/29f6ef3049fe1ce603fcd90f9dbfe1827ee5dbb9/common/helpers.go#L105-L113) off the `resultCh` has or is exiting due to the context being closed. We don't want [this goroutine](https://github.com/grafana/xk6-browser/blob/4350722189cf533a31228ff0c032b88f14ae394b/common/element_handle.go#L1648-L1652) to be hanging around waiting since nothing will read off the `resultCh` or `errCh`.
Updates: https://github.com/grafana/xk6-browser/issues/1437
=> Fix write channel to exit when ctx is done

.github/ISSUE_TEMPLATE/team_issues.yaml
- Adds the task of updating release tasks
- Improves some wording
Updating the release tasks might help the k6 release coordinator ensure that every update to the k6, k6-docs, etc., is provided.
=> Update team issues template

examples/colorscheme.js, examples/cookies.js, examples/device_emulation.js, examples/dispatch.js, examples/elementstate.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/hosts.js, examples/pageon.js, examples/querying.js, examples/shadowdom.js, examples/waitforfunction.js
Updates sync examples with `check` to async `check`.
Some of the examples don't require an async check, but it's better to use async `check` in them for consistency.
The sync k6 `check` is cumbersome when working with async functions.
grafana/k6-docs#1725
=> Update sync examples with `check` to async `check`

.github/ISSUE_TEMPLATE/team_issues.yaml
`Description` should be `description` as Github says:
> Property Description is not allowed.yaml-schema: textarea attributes
Somehow, the team template doesn't appear while creating an issue. This might be the reason.
=> Fix the team issue template

common/keyboard.go, keyboardlayout/us.go, tests/keyboard_test.go, tests/static/page1.html, tests/static/page2.html
This will allow us to write the test for all platforms that either work with Control or Meta when performing keyboard actions. E.g. Control+click on windows, and meta+click on mac to open a link in a new window.
It allows us to do the following on windows, linux and mac without checking which platform the script is ran on in the test script itself to choose the correct meta key (control or meta):
```js
import { browser } from "k6/browser";
scenarios: {
ui: {
executor: "shared-iterations",
options: {
browser: {
type: "chromium",
},
},
},
}
};
const page = await browser.newPage();
await page.goto("https://test.k6.io/");
await page.keyboard.down('ControlOrMeta');
// Open the link in a new tab.
// Wait for the new page to be created. …
```
=> Add ControlOrMeta helper key

browser/request_mapping.go, browser/sync_request_mapping.go, common/http.go, common/http_test.go
Refactor `sobek` out of `request.headerValue`.
Makes the codebase more maintainable where `sobek` code is within the mapping layer and not in the main business logic.
Updates: https://github.com/grafana/xk6-browser/issues/1275
=> Refactor sobek out of request type

browser/keyboard_mapping.go, browser/sync_keyboard_mapping.go, browser/sync_page_mapping.go, common/keyboard.go, common/keyboard_test.go, tests/keyboard_test.go
Remove Sobek from the keyboard type.
Keeps things more maintainable.
Updates: https://github.com/grafana/xk6-browser/issues/1277
=> Refactor sobek out of keyboard

common/connection.go
Remove sobek from `connection.Close`.
It's not needed. Keeps things more maintainable.
Updates: https://github.com/grafana/xk6-browser/issues/1281
=> Refactor sobek out of connection.Close

common/js/injected_script.js
=> Enhance waitForSelector JavaScript error message

browser/metric_event_mapping.go, browser/metric_mapping.go, browser/page_mapping.go, browser/sync_page_mapping.go, common/frame_session.go, common/network_manager.go, common/network_manager_test.go, common/page.go, examples/pageon-metric.js, tests/page_test.go, tests/remote_obj_test.go
This adds the functionality to group url tags by intercepting all metrics that the **browser module** emits, compare and match with the supplied regex(s), and then set the `name` and `url` tags with the new name supplied by the user in the script.
A lot of websites will perform requests that contain dynamic parts in the request url, which could be ids that are generated on every new session, account ids, or for cache busting purposes.
This will help in two ways:
1. Avoids high cardinality issues where tests work with websites with a lot of these dynamic urls.
2. It becomes trivial to correlate urls which are for the same page but contain dynamic parts in the url (ids/cache busting/etc).
The user first needs to register an event handler:
```mermaid
sequenceDiagram
box main goroutine …
```
=> Add page.on('metric')

common/http.go, common/http_test.go, go.mod, go.sum
Update cdp dependency.
We're working with a 2 year old CDP dependency library. Updating to the latest one to ensure that we don't miss any new fixes, features etc.
Updates: https://github.com/grafana/xk6-browser/issues/1430
=> Update cdp dependency

common/page.go, tests/tracing_test.go
This instruments `page.waitForTimeout` with tracing.
We do this so that we can identify when a test is waiting/sleeping.
Updates: https://github.com/grafana/xk6-browser/issues/1426
=> Add tracing to page.waitForTimeout

browser/mapping_test.go, browser/metric_event_mapping.go, browser/page_mapping.go, common/page.go, examples/pageon-metric.js, tests/page_test.go
1. Conforms the `page.on` event mappings to the existing mappers.
2. Adds a test for the metric mapping.
This will be needed when generalizing the `page.on` API events. To be generalized, all mappers need to be in the same signature. This is a part of [the suggestions](https://github.com/grafana/xk6-browser/issues/1227#issuecomment-2393348036).
Updates: #1227
=> Unify `page.on` event mappings

browser/mapping_test.go, browser/page_mapping.go, browser/sync_page_mapping.go, common/page.go, tests/page_test.go, tests/remote_obj_test.go
Generalizes `page.on` events.
- To provide more type-safety.
- Get rid of runtime type assertions.
- Easy to extend for other `page.on` event types.
Updates: #1227
=> Generalize `page.on` event

browser/mapping_test.go, browser/page_mapping.go, browser/sync_page_mapping.go, common/page.go
Add and use `PageOnEventName`.
For greater readability, clarity, and type safety at the compile time.
Updates: #1227
=> Refactor to type safe `page.on` event names

common/frame.go, common/locator.go
We're allowing retries on `waitFor` when the following errors occur when `waitFor` is waiting:
- "Inspected target navigated or closed"
- "Cannot find context with specified id"
- "Execution context was destroyed"
To prevent a stack overflow, it will retry for a maximum of 20 times before failing. In my tests i've seen the retry count drop from 20 to 12 at most. I feel 20 is a safe number that shouldn't be reached in normal SSO login flows. I want to avoid using a larger retry count to force us to fix this permanently asap.
This PR fixes an issue where `waitFor` fails to wait while the underlying page it is waiting on is navigating. A common scenario where we might see this is during a login/logout flow using SSO. The initial page will be redirected multiple times until we get to the …
=> Add workaround to retry `waitFor` until it is success or retry count is 0

browser/console_message_mapping.go, browser/mapping_test.go, browser/metric_event_mapping.go, browser/page_mapping.go
Improves namings in `page.on` mapping.
To improve clarity and provide the first step for the `page.on` generalization work.
Updates: #1227
=> Refactor `page.on` mapping names

browser/page_mapping.go
Generalize `page.on` events.
To streamline the addition and running of additional `page.on` events.
Updates: #1227
=> Streamline the addition and running of new `page.on` events

common/frame_session.go, common/network_manager.go, common/network_manager_test.go, common/page.go
Refactor `page.on` event handling.
https://github.com/grafana/xk6-browser/pull/1456#discussion_r1790661370
Updates: #1227
=> Refactor `page.on` event handling

common/event_emitter.go
When we read off the read queue, we alias the slice. What has been forgotten though is to remove the reference to the entry in the slice after it has been read. This fixes that by overwriting the entry with a new Event. This now allows the GC to pick up the buffered data that the event was holding onto.
This is removing the reference to the data that is no longer needed once the Event has been sent and read off the queue,. but before the read queue is aliased.
I remember having this complicated [write/read slice in the emitter queue](https://github.com/grafana/xk6-browser/blob/35e50b8a9d365cbe7dbe2d49e070647729c2571b/common/event_emitter.go#L74-L77). The reason we needed this to keep the incoming CDP messages in order, otherwise they would go out of order …
=> Fix memory leak in queue

browser/mapping_test.go, browser/metric_event_mapping.go, common/page.go, examples/pageon-metric.js, tests/page_test.go
This change does two things:
1. Moves the `name` field to the level above.
2. Rename the `urls` field to `matches`.
So from:
```js
page.on('metric', (metric) => {
metric.tag({
urls: [
{url: /^https:\/\/test\.k6\.io\/\?q=[0-9a-z]+$/, name:'test'},
]
});
});
```
to:
```js
page.on('metric', (metric) => {
metric.tag({
name:'test',
matches: [
{url: /^https:\/\/test\.k6\.io\/\?q=[0-9a-z]+$/},
]
});
});
```
It was unclear what `name` was doing when it was part of the "`match`" object and it made it difficult to add other fields to the object to match against.
`urls` doesn't lend itself to extending with more fields to match against. It also doesn't represent what it is doing, whereas `matches` is a helpful verb that makes it clearer to the user/reader of the API what its impact is.
By moving the …
=> Move the name field on the `page.on('metric') API

common/frame_session.go, common/network_manager.go, common/network_manager_test.go, common/page.go, examples/pageon-metric.js, tests/page_test.go
This change adds a new field to the `Match` object in `page.on('metric')`. It allows the user to add the request method to it so that the tagging can be fine tuned to group requests with the same url and method. `method` is an optional field, and if it's not defined then the grouping will be done for all urls that match regardless of the request method.
```js
page.on('metric', (metric) => {
metric.tag({
name:'ping-1',
matches: [
{url: /^http:\/\/127\.0\.0\.1\:[0-9]+\/ping\?h=[0-9a-z]+$/, method: 'GET'},
]
});
});
```
The use case for this is when requests are made against the same URL but with different request methods. A simple example is a `PUT` to `/cart/123` to add an item to the cart, and a `GET` to `/cart/123` to retrieve the cart.
Updates: …
=> Add method field on Match object for `page.on('metric')`

browser/page_mapping.go
Adding a `context.Done()` check so that when the context is closed we can carry on with shutting down of the iteration and not wait for the task to run (which will not happen since the taskqueue will have also been shutdown either from [here](https://github.com/grafana/xk6-browser/blob/f757283a54096ce3868d6fec13eebc4b6f1fd6ff/browser/page_mapping.go#L45), or [here](https://github.com/grafana/xk6-browser/blob/8fce16a75360a2317dfe2ff4c8ac4e5a2c292b5b/browser/registry.go#L549-L555)).
If the taskqueue is closed before all the tasks are read from the queue, the remaining tasks on the queue will not be read and executed and so the done channel will not be closed causing the goroutine to wait forever.
Updates: https://github.com/grafana/xk6-browser/issues/1480
=> Fix memory leak caused by taskqueue closing before all tasks are executed

browser/browser_context_mapping.go
Adding a `context.Done()` check so that when the context is closed we can carry on with shutting down of the iteration and not wait for the task to run (which will not happen since the taskqueue will have also been shutdown either from [here](https://github.com/grafana/xk6-browser/blob/f757283a54096ce3868d6fec13eebc4b6f1fd6ff/browser/page_mapping.go#L45), or [here](https://github.com/grafana/xk6-browser/blob/8fce16a75360a2317dfe2ff4c8ac4e5a2c292b5b/browser/registry.go#L549-L555)).
If the taskqueue is closed before all the tasks are read from the queue, the remaining tasks on the queue will not be read and executed and so the done channel will not be closed causing the goroutine to wait forever.
Related: https://github.com/grafana/xk6-browser/pull/1493
=> Fix waitForEvent when taskqueue closed before the task is executed

browser/page_mapping.go, browser/sync_page_mapping.go, common/page.go, tests/page_test.go, tests/remote_obj_test.go
This adds an error return value from the `page.on` handlers.
It's being more defensive to ensure that when an error occurs (due to the iteration ending) we exit early and don't try to process any other handlers, and to ensure that we don't use incorrect url name values when a `page,.on(metric)` handler returns early.
Relates to: https://github.com/grafana/xk6-browser/pull/1493#discussion_r1806534456
=> Add error return value from `page.on` handlers

common/browser_context.go, common/browser_context_options.go, common/browser_context_test.go, tests/browser_context_options_test.go
Users can set where to download files.
```javascript
const context = await browser.newContext({
acceptDownloads: true,
downloadsPath: '/my/directory',
});
```
If `downloadsPath` is unset, we create a temporary directory for each `BrowserContext` with the `k6-browser-artifacts-` prefix. Note that we do this for every call to `NewBrowserContext`.
- Finding the downloaded files without `downloadPaths` can be difficult.
- Allow users to download files to a specific directory they want.
- To create a temporary directory to save the downloaded files.
Updates: #1289
=> Add `browserContext.downloadsPath`

k6ext/promise.go
This changes the promise helpers so after grafana/k6#4017 async code and Interrupt will work.
AbortingPromises seems to have not been used at all and just adds complexity. And `promises.New()` already does the remaining things needed to happen, so this can be merged even without grafana/k6#4017.
=> Refactor promise helpers to fix Interrupt with async code

browser/browser_context_mapping.go, browser/mapping_test.go, common/browser_context.go, common/browser_context_options.go, common/network_manager.go
=> Desobekify `BrowserContext` methods

browser/browser_context_mapping.go, browser/sync_browser_context_mapping.go, common/browser_context_options.go
- Moves `BrowserContext` waitForEvent Sobek-option parsing into the mapping layer.
- Removes `common.WaitForEventOptions` as it's only used in the mapping.
See "Desobekifying Sobek transformation" in #1064.
#1270
=> Desobekify `BrowserContext` wait for event options

browser/browser_context_mapping.go, browser/browser_mapping.go, common/browser_context.go, common/browser_context_options.go
- Desobekify `BrowserContext` geolocation.
- Use Sobek translation directly instead of manual parsing.
See "Desobekifying Sobek transformation" in https://github.com/grafana/xk6-browser/issues/1064.
- #1270
=> Desobekify `BrowserContext` geolocation

tests/keyboard_test.go
Fix `TestKeyboardPress` test panic.
This only fixes the panic but not the underlying error with `WaitForEvent`. As we can also see in #1506, there is clearly an issue with `WaitForEvent`.
This fix highlights the fact that we should use `require` instead of `assert` when an error should block the test from continuing.
Updates #1505
=> Fix `TestKeyboardPress` test panic

browser/browser_mapping.go, common/browser_context_options.go, common/page.go, tests/browser_context_options_test.go
- Desobekify `Screen`.
- Turn `Screen` into a value type.
See "Desobekifying Sobek transformation" at https://github.com/grafana/xk6-browser/issues/1064.
- #1270
=> Desobekify `Screen`

common/browser_context_options.go
Removes the forgotten `Geolocation.Parse`.
Not used anymore.
- #1270
=> Removes the forgotten `Geolocation.Parse`

browser/keyboard_mapping.go, browser/sync_keyboard_mapping.go, common/element_handle.go, common/frame_options.go, common/keyboard.go, common/keyboard_options.go, common/keyboard_test.go, tests/keyboard_test.go
- Desobekify `KeyboardOptions`.
- Turn `KeyboardOptions` into a value type.
See "Desobekifying Sobek transformation" at https://github.com/grafana/xk6-browser/issues/1064.
The linter warning is a false alarm.
- #1522
- #1270
=> Desobekify `KeyboardOptions`

common/network_manager.go
Remove the unused `NetworkManager.ExtraHTTPHeaders` method.
Unused.
- #1282
=> Remove unused `NetworkManager.ExtraHTTPHeaders` method

browser/browser_context_options_test.go, browser/browser_mapping.go, browser/helpers.go, browser/sync_browser_mapping.go, common/browser.go, common/browser_context.go, common/browser_context_options.go, tests/browser_context_options_test.go, tests/element_handle_test.go, tests/network_manager_test.go
Refactor `parseBrowserContextOptions` to use direct Sobek transformation.
After the refactorings we made in #1270, it's now possible to let Sobek perform this transformation alone.
I also used the script to test it using my old friend `Printf` in `Browser.NewContext` etc..
```javascript
export default async function() {
const context = await browser.newContext({
acceptDownloads: true,
downloadsPath: "/tmp",
bypassCSP: true,
colorScheme: "dark",
deviceScaleFactor: 1,
extraHTTPHeaders: {
"X-Header": "value",
},
geolocation: { latitude: 51.509865, longitude: -0.118092 },
hasTouch: true,
httpCredentials: { username: "admin", password: "password" },
ignoreHTTPSErrors: true,
isMobile: true,
javaScriptEnabled: true,
locale: "fr-FR",
offline: true,
permissions: ["camera", "microphone"], …
```
=> Refactor `parseBrowserContextOptions` to Sobek

common/frame.go, common/locator.go
This fixes an issue with APIs that use the underlying `frame.waitForSelector`. It does this by reusing `frame.waitFor` which contains a [fix](https://github.com/grafana/xk6-browser/pull/1469) to retry on certain errors which can occur when a navigation is taking place while also waiting for the selector.
This makes several APIs more robust when called during or after a navigation to a new page. I believe the list covers most of the APIs that this fix applies to:
- `frame.WaitForSelector`
- `locator.IsChecked`
- `locator.DispatchEvent`
- `locator.Fill`
- `locator.Focus`
- `locator.GetAttribute`
- `locator.InnerHTML`
- `locator.InnerText`
- `locator.InputValue`
- `locator.IsEditable`
- `locator.IsEnabled`
- `locator.IsDisabled`
- `locator.Press`
- `locator.SelectOption`
- …
=> Fix underlying `frame.waitForSelector`

common/browser.go, common/browser_context.go, examples/useragent.js, tests/browser_test.go
Sets up `Browser.UserAgent` to return a user agent without `Headless`.
See #1497.
Updates #1497.
=> Remove `Headless` from user agent

browser/frame_mapping.go, common/frame.go, tests/frame_test.go
The fixes involves casting the value from evaluate to a string, and if that doesn't cast to a string we should return an error. The cast was missing from the earlier implementation.
Calling `frame.title` causes an error since the value returned from evaluate is an `interface{}` and not a string.
=> Fix frame.title

tests/browser_context_test.go
Removes deprecated accessibility events from tests.
This feature [has been deprecated](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/permissions/permission_utils.h;l=37;drc=60130be50f68c89220d8ace62c87155025267a2c;bpv=1;bpt=1
) and was causing `TestBrowserContextGrantPermissions` to fail.
https://github.com/grafana/xk6-browser/actions/runs/11856978357/job/33044367991?pr=1540
=> Remove deprecated accessibility events

common/frame_manager.go
Making it simpler to read the if in `frameNavigated` which always confuses me. Using De Morgan's Law, `(A || B) == (!A && !B)`.
Make it easier to read.
=> Refactor if to make it easier to read

common/frame_manager.go
The change fixes a panic by returning nil instead of erroring.
If the frame is nil at this point, then the cause of this is likely due to chrome not sending a frameAttached event ahead of time. This isn't a bug in chrome, and seems to be intended behavior. Instead of worrying about the nil frame and causing the test to fail when the frame is nil, we can instead return early. The frame will be initialized when getFrameTree CDP request is made, which will call onFrameAttached and onFrameNavigated.
https://github.com/grafana/xk6-browser/issues/1500
=> Fix frame panic

browser/frame_mapping.go, browser/helpers.go, browser/helpers_test.go, browser/js_handle_mapping.go, browser/page_mapping.go, tests/page_test.go
Add missing function arguments check to `JSHandle` mapping.
#1543 
Updates #1543
=> Fix `mapJSHandle` invalid memory address or nil pointer dereference

common/element_handle.go, common/page.go, common/screenshotter.go
* Migrate screenshoter from [deprecated `visualViewport`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getLayoutMetrics) to `cssVisualViewport`. 
* Fallback to defaults in the case of `visualViewport` is nil. This is an arguable change since it's partially hiding the issue, on the other side my rational was it's better to make a screenshot with defaults, rather than erroring it. Open to discussion.
* Unfortunately, wasn't able to reproduce that's why no tests
Currently, we have an issue with panicing #1502
Part of #1502
=> Handle panic in screenshoter

.github/workflows/e2e.yml, .github/workflows/sync_e2e.yml, .github/workflows/test.yml
Stop the scheduled CI test runs.
This was placed here to keep track of k6 breaking changes. Now that the xk6-browser codebase has been merged into k6 this isn't needed.
=> Remove the CI schedule
