grafana/xk6-browser

README.md
=> Fix readme for k6 install

common/network_manager.go, common/request.go, common/request_test.go
This is easier to work with for e.g. scheme comparisons, the parsing is done only once, and will now be properly logged if it fails.
=> Make `Request.url` into a `url.URL`

README.md
To be consistent with https://github.com/grafana/k6/pull/2233
=> [content] minor readme change

README.md
This might not have been clear enough. See #112.
=> Clarify installation instructions in README

common/response.go
This would race between e.g. Response.Body() and Response.bodySize().
This is the same fix from #117, just extracted since that PR might take a while to merge and this is happening on `main`: https://github.com/grafana/xk6-browser/runs/4252339240
=> Fix data race on Response.body

common/browser_context.go
I cherry-picked this one from #129 as a separate PR.
@imiric So let's merge this one before merging #129.
=> Fix k6Throw calls in BrowserContext

common/barrier_test.go, common/browser.go, common/browser_context.go, common/connection.go, common/element_handle.go, common/execution_context.go, common/frame.go, common/frame_manager.go, common/frame_session.go, common/frame_test.go, common/helpers_test.go, common/page.go, common/request.go, common/session.go
I cherry-picked this one from #129 as a separate PR.
@imiric So let's merge this one before merging #129.
=> Improve logs 20211203 (cherry picked)

common/frame_manager.go, common/frame_test.go
=> Fix frameAbortedNavigation: nil pendingDocument

common/frame.go
=> Enhance waitForSelector error messages

README.md
=> Update xk6-browser usage in README

common/session.go
=> Fix silence deprecated chromium event logging

README.md, main.go, release notes/v0.2.0.md
This adds release notes and changes to the README for the new release.
=> Release v0.2.0

ROADMAP.md
This is an RFC of what we had previously discussed. It's best viewed as rendered HTML if you click on "View file".
Let me know if I missed anything, if the timelines don't align with what you had in mind, or if anything else should be changed.
=> Add initial roadmap document

go.mod, go.sum
`go.mod` had unused modules and `go mod tidy` cleaned it up.
=> Remove unused modules

tests/locator_test.go
Resolves: https://github.com/grafana/xk6-browser/pull/365#discussion_r888846062
=> Refactor locator.Check and Uncheck tests into one

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
Reverts grafana/xk6-browser#385
=> Revert "Add locator.focus"

tests/locator_test.go
Resolves: https://github.com/grafana/xk6-browser/pull/388#discussion_r894552608
Resolves: https://github.com/grafana/xk6-browser/pull/372#discussion_r890936907
Related: #366
=> Refactor locator tests to run in parallel

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
=> Add locator.innerText

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
=> Add locator.textContent

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
=> Add locator.inputValue

common/frame.go, common/locator.go
This changes the error messages in `Frame` and `Locator`.
Related discussions:
* https://github.com/grafana/xk6-browser/pull/286#discussion_r866890577
* https://github.com/grafana/xk6-browser/pull/395#discussion_r896530637
=> Refactor error messages in frame and locator

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
=> Add locator.press

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go
=> Add locator.type

api/locator.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
=> Add locator.hover

api/locator.go, common/element_handle.go, common/frame.go, common/locator.go, tests/locator_test.go, tests/static/locators.html
=> Add locator.tap

api/locator.go, common/locator.go, tests/locator_test.go
=> Add locator.waitFor

tests/locator_test.go, tests/test_browser.go
This PR is for #366's "Goja bool check" task.
=> Refactor locator tests: goja bool check

tests/locator_test.go
=> Refactor locator tests to table tests

README.md, examples/browser_args.js, examples/browser_on.js, examples/colorscheme.js, examples/device_emulation.js, examples/elementstate.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/locator.js, examples/locator_pom.js, examples/querying.js, examples/screenshot.js, examples/waitforfunction.js, main.go
This PR closes #460. Please see the issue for details.
=> Make chromium importable

README.md, api/element_handle.go, api/frame.go, api/page.go, common/element_handle.go, common/frame.go, common/page.go, examples/fillform.js, tests/element_handle_test.go, tests/frame_manager_test.go, tests/launch_options_slowmo_test.go
=> Async click

main.go
This will allow us to enable pprof in any environment where we need to
keep an eye on what is going on, especially since we need to track down
some race conditions during long runs.
=> Add pprof server and protect it with an env var

README.md
Fixes https://github.com/grafana/xk6-browser/issues/301
=> docs: update README to include an mp4 video

chromium/browser_type.go, common/browser_process.go, common/connection.go, common/kill_linux.go, common/kill_other.go
These are minor changes I did while working on #510 / #232. See the commits for details.
=> Minor BrowserType and Connection refactor

common/network_manager.go
=> Fix onLoadingFinished reqFromParent nil check

common/browser.go
=> Check session for nilness before making a page from it

api/frame.go, api/page.go, common/frame.go, common/frame_manager.go, common/page.go, examples/browser_args.js, examples/browser_on.js, examples/colorscheme.js, examples/device_emulation.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/locator.js, examples/locator_pom.js, examples/multiple-scenario.js, examples/querying.js, examples/screenshot.js, tests/browser_context_options_test.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/launch_options_slowmo_test.go, tests/locator_test.go, tests/network_manager_test.go, tests/page_test.go, tests/test_browser.go
=> Implement async goto

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feat_req.yaml
Mostly copied from the k6 repo.
=> Add GitHub issue template

tests/browser_context_options_test.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/launch_options_slowmo_test.go, tests/locator_test.go, tests/network_manager_test.go, tests/page_test.go, tests/test_browser.go
Mihail did a great job adding promise test helpers to the test browser test suite 👏  I refactored some parts of the test promises to make it slightly more readable (hopefully). But I'm open to suggestions.
=> Refactor testPromises

examples/browser_args.js, examples/colorscheme.js, examples/device_emulation.js, examples/evaluate.js, examples/getattribute.js, examples/grant_permission.js, examples/multiple-scenario.js, examples/querying.js, examples/screenshot.js, examples/waitforfunction.js
=> Fix example scripts for premature closing

common/browser_options.go, common/browser_options_test.go, common/launch.go, common/launch_test.go, common/options.go
Please see issue #605 for details.
I happened to fix-ed #407 while I was working on this PR. Ankur (since #407 was assigned to you), I can post the fix in a different PR if you don't mind.
**Tasks:**
Closes #605
=> Parse BrowserType.Launch options and return errors

common/frame_manager.go
The inflight request map is being populated in a non safe way without a lock in place. Although we can easily fix the race condition, the data store in the map isn't being used anywhere, so it's better to remove it.
Closes: https://github.com/grafana/xk6-browser/issues/680
=> Remove the unused unsafe inflight request map

browser/mapping.go, browser/mapping_test.go
Now we can fix #695 based on this.
Fixes: #698
=> Fix k6 browser mappings due to goja async update

go.mod, go.sum
This version contains the much await await/async keyword support.
=> Update to the latest version of k6

examples/browser_args.js, examples/colorscheme.js, examples/device_emulation.js, examples/evaluate.js, examples/fillform.js, examples/getattribute.js, examples/grant_permission.js, examples/hosts.js, examples/locator.js, examples/locator_pom.js, examples/multiple-scenario.js, examples/querying.js, examples/screenshot.js, examples/waitforfunction.js
Note that, IMO, `examples/browser_on.js` does not need to be converted to async/await. I experimented with it, but it didn't look good. Be my guest if you have any ideas :)
Closes: #697
=> Convert promisified (.then()) examples to async/await

api/element_handle.go, api/frame.go, api/page.go, browser/mapping.go, common/element_handle.go, common/frame.go, common/page.go, tests/element_handle_test.go, tests/frame_manager_test.go, tests/frame_test.go, tests/launch_options_slowmo_test.go, tests/lifecycle_wait_test.go
=> Map [Page|ElementHandle|Frame|Locator].Click promises and fix tests

browser/mapping.go, browser/mapping_test.go
=> Map forgotten types

api/page.go, browser/mapping.go, browser/mapping_test.go, common/page.go, examples/keyboard.js, examples/mouse.js, examples/touchscreen.js, tests/keyboard_test.go
=> Map Page's Keyboard, Mouse, and Touchscreen properties

common/browser_context.go, tests/browser_context_test.go, tests/static/add_cookies.html
Closes #5
Signed-off-by: zookee <z.persboy@gmail.com>
=> Add implementation for adding cookies

browser/mapping_test.go
Adds the forgotten Locator API test to the mapping tests.
=> Add locator mapping test

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template as per @inancgumus's suggestion to use tasklist for better integration with Github.
=> chore: update pr template to use task list

tests/webvital_test.go
Since we now send metrics each time they fire up, we need to adjust the test accordingly. I thought we would need this fix, I couldn't resist doing it before my leave :) Sorry for the inconvenience :(
Please feel free to modify the PR commits.
Related: #914.
=> Fix web vital test bug while receiving metrics

common/network_manager.go
Continuing/Failing a request from `onRequestPaused` happens when CDP's `network.fetch` functionality is [enabled](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable) and therefore k6 browser acts as a proxy for every request that matches the specified pattern. This is the case when [hostnames](https://k6.io/docs/using-k6/k6-options/reference/#block-hostnames) or [IPs](https://k6.io/docs/using-k6/k6-options/reference/#blacklist-ip) blacklists are set for a test run.
A `context.Canceled` error here happens most probably because the iteration has ended, closing the browser's context inherited by `NetworkManager`, meanwhile the continue/fail CDP command is being executed.
Given this situation, and considering that this happens often in sites that are continuously …
=> Avoid `onRequestPaused` error log when ctx canceled

README.md
Please describe your pull request.
=> update README.md to point to the correct grafana community forum

.github/dependabot.yml
=> Remove ka3de from reviewers

browser/module.go
Update package browser comment with a new message.
For clarity. See https://github.com/grafana/xk6-browser/pull/1203#discussion_r1478548132.
=> Update package browser comment for clarity

tests/browser_test.go
- Better detection for existing processes.
Before this fix, this test was [failing on CI](https://github.com/grafana/xk6-browser/actions/runs/8000668240/job/21853954237?pr=1219) because of the error "process is already finished". This test is about checking if a process is dead already. So, no need to send a dead process another `Signal(0)` to check if it's dead.
This has fixed the issue—here's an [example](https://github.com/grafana/xk6-browser/actions/runs/8002205471/job/21854943046?pr=1223).
=> Fix TestMultiBrowserPanic existing process detection

browser/mapping.go, browser/mapping_test.go, examples/touchscreen.js
=> Async `Tap`

browser/mouse_mapping.go
=> Async `Mouse`

browser/request_mapping.go
https://github.com/grafana/xk6-browser/issues/1308.
See https://github.com/grafana/xk6-browser/issues/428.
=> Async `request`

k6ext/k6test/vu.go, tests/browser_test.go, tests/page_test.go, tests/webvital_test.go
Fixes a few of the integration tests that were failing often locally (not related to CI flakey tests, but it might help there too).
Better DX.
=> Fix a few integration tests that failed often

examples/throttle.js
Updating the threshold to avoid the CI failures.
To avoid the CI failures.
=> Update threshold to avoid failures in CI

browser/registry.go
We don't want to shadow the vuCtx here since it breaks the abort causing NPD.
=> Fix vuCtx shadowing

common/page.go
A quick fix to make `main` work again 🤦
=> Fix MetricEvent.Tag input
